import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';import {supplierRecord} from '../services/api/src/suppliers.js';
const browser=await chromium.launch({args:['--no-sandbox']});fs.mkdirSync('qa',{recursive:true});
try{for(const width of [1440,390]){
 const context=await browser.newContext({viewport:{width,height:1000}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));let checkoutEnabled=true;let suppliers=[];let support=[{id:'request-test',order_id:'order-test',kind:'return',message:'طلب إرجاع منتج تجريبي للمراجعة',status:'pending',customer_reply:''}];
 const manualOrder={id:'00000000-0000-0000-0000-000000000001',order_number:'LOCAL-TEST',customer_name:'عميل تجربة',whatsapp_phone:'01012345678',address:'عنوان تجريبي',governorate:'FAYOUM',total:145,status:'pending',payment_status:'unpaid'};
 const orderHistory=[];
 await page.route('https://store-api.example.invalid/**',async route=>{
  const req=route.request(),url=new URL(req.url());let body,status=200;
  if(req.method()==='OPTIONS')return route.fulfill({status:204,headers:{'access-control-allow-origin':'*','access-control-allow-headers':'content-type,x-admin-key,authorization,idempotency-key','access-control-allow-methods':'GET,POST,PATCH,OPTIONS'}});
  if(url.pathname.startsWith('/admin/')&&req.headers()['x-admin-key']!=='test-only-key'){body={error:'unauthorized'};status=401;}
  else if(url.pathname==='/admin/suppliers'){
   if(req.method()==='POST'){try{const row={id:'supplier-test',...supplierRecord(req.postDataJSON())};suppliers.push(row);body=row;status=201;}catch{body={error:'invalid_supplier_record'};status=400;}}
   else body=suppliers;
  }else if(url.pathname==='/admin/orders')body=[manualOrder];
  else if(url.pathname===`/admin/orders/${manualOrder.id}/details`)body={items:[{id:1,product_id:'product-test',title:'كوتشي اختبار',sku:'TEST-SHOE-41-BLACK',size:'41',color:'أسود',quantity:2,unit_price:55}],history:orderHistory,catalogDetailsAreCurrent:true};
  else if(url.pathname===`/admin/orders/${manualOrder.id}/status`&&req.method()==='PATCH'){const change=req.postDataJSON();if(change.expected_status!==manualOrder.status){status=409;body={error:'order_changed'};}else{orderHistory.unshift({id:orderHistory.length+1,action:'manual_order_status_update',details:{from:manualOrder.status,to:change.status,note:change.note},created_at:new Date().toISOString()});manualOrder.status=change.status;body={id:manualOrder.id,status:manualOrder.status,payment_status:manualOrder.payment_status};}}
  else if(url.pathname==='/admin/kpis')body={grossSales:100,totalOrders:1};
  else if(url.pathname==='/delivery-interest'){assert.equal(req.postDataJSON().governorate,'CAIRO');body={recorded:true,orderCreated:false};status=202;}
  else if(url.pathname==='/admin/alerts')body={deliveryDemand:[{region:'CAIRO',interest_count:2,blocked_count:1,last_signal:new Date().toISOString()}],alerts:[{id:'order:sample',title:'طلب جديد يحتاج متابعة',detail:'طلب تجريبي',at:new Date().toISOString()}]};
  else if(url.pathname==='/admin/support')body=support;
  else if(url.pathname==='/admin/support/request-test'&&req.method()==='PATCH'){Object.assign(support[0],req.postDataJSON());body=support[0];}
  else if(url.pathname.startsWith('/orders/order-test/')){
   if(req.headers().authorization!=='Bearer invoice:test-invoice-token'){status=403;body={error:'forbidden'};}
   else if(url.pathname.endsWith('/status'))body={id:'order-test',order_number:'TEST-ORDER',status:'delivered',payment_status:'paid',payment_method:'wallet',total:100,shipment:null};
   else if(url.pathname.endsWith('/support')){if(req.method()==='POST'){const data=req.postDataJSON();const row={id:'customer-request',order_id:'order-test',kind:data.kind,message:data.message,status:'pending',customer_reply:''};support.push(row);body={id:row.id,status:row.status};status=201;}else body=support;}
  }
  else if(url.pathname==='/products')body=[{id:'product-test',sku:'TEST-SHOE',title_ar:'كوتشي تجربة نطاق التوصيل',category_slug:'shoes',retail_price:110,stock_quantity:1,image_url:'/icon.svg'}];
  else if(url.pathname==='/categories'||url.pathname==='/admin/products')body=[];
  else if(url.pathname==='/capabilities')body={checkoutEnabled,onlinePayment:false,deliveryGovernorates:['FAYOUM'],deliveryAreas:{FAYOUM:[{code:'FAYOUM_CITY',label:'مدينة الفيوم'},{code:'SENOURIS',label:'مدينة سنورس'},{code:'TAMIYA',label:'مدينة طامية'},{code:'ITSA',label:'مدينة إطسا'},{code:'ABSHWAY',label:'مدينة أبشواي'}]}};else body=null;
  await route.fulfill({status,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify(body)});
 });
 await page.goto(process.env.TEST_WEB_URL||'http://127.0.0.1:4173/');await page.evaluate(()=>scrollTo(0,document.body.scrollHeight));await page.getByRole('button',{name:'دخول الإدارة'}).click();await page.getByPlaceholder('Admin API Key').fill('test-only-key');await page.getByRole('button',{name:'دخول آمن'}).click();const bounds=await page.locator('.admin-workspace').boundingBox();assert.ok(Math.abs(bounds.x)<=1);assert.ok(Math.abs(bounds.y)<=1);assert.ok(bounds.width>=width-2);assert.ok(bounds.height>=998);await page.getByRole('button',{name:'الموردون'}).click();await page.getByRole('button',{name:'إضافة مورد أو تاجر'}).click();
 await page.getByLabel('اسم المورد أو المتجر',{exact:true}).fill('مورد التجربة');await page.getByLabel('الهاتف',{exact:true}).fill('01012345678');await page.getByLabel('طريقة إتمام الشراء').selectOption('visit');await page.getByLabel('عنوان الزيارة أو الاستلام').fill('عنوان تجريبي');await page.getByLabel('الحد الأدنى للشراء').fill('10');await page.getByLabel('تأكدت أن المورد يبيع قطعة واحدة').check();await page.getByRole('button',{name:'حفظ المورد',exact:true}).click();await page.getByText('تعذر الحفظ.',{exact:false}).waitFor();assert.equal(suppliers.length,0);
 await page.getByLabel('الحد الأدنى للشراء').fill('1');await page.getByRole('button',{name:'حفظ المورد',exact:true}).click();await page.getByText('تم حفظ المورد',{exact:true}).waitFor();assert.equal(suppliers.length,1);assert.equal(suppliers[0].order_method,'visit');assert.equal(suppliers[0].allows_single_units,true);
 await page.getByRole('button',{name:'الطلبات',exact:true}).click();await page.getByRole('heading',{name:'طلب LOCAL-TEST',exact:true}).waitFor();await page.getByRole('button',{name:'عرض المنتجات وسجل المتابعة',exact:true}).click();await page.getByRole('heading',{name:'كوتشي اختبار — TEST-SHOE-41-BLACK',exact:true}).waitFor();await page.getByText('المقاس: 41 — اللون: أسود',{exact:true}).waitFor();await page.getByText('لا توجد إجراءات إدارية مسجلة لهذا الطلب.',{exact:true}).waitFor();await page.getByLabel('ملاحظة المتابعة').fill('تم تأكيد العنوان وتوفر المنتج');await page.getByRole('button',{name:'حفظ حالة الطلب',exact:true}).click();await page.getByText('حالة الطلب: جارٍ التجهيز — الدفع: لم يُدفع',{exact:true}).waitFor();assert.equal(manualOrder.status,'processing');await page.getByLabel('الحالة الجديدة').selectOption('delivered');await page.getByLabel('ملاحظة المتابعة').fill('تم تسليم المنتج محليًا للعميل');await page.getByRole('button',{name:'حفظ حالة الطلب',exact:true}).click();await page.getByText('حالة الطلب: تم التسليم — الدفع: لم يُدفع',{exact:true}).waitFor();assert.equal(manualOrder.payment_status,'unpaid');assert.equal(await page.getByRole('button',{name:'حفظ حالة الطلب',exact:true}).count(),0);await page.getByRole('button',{name:'عرض المنتجات وسجل المتابعة',exact:true}).click();await page.getByText('الملاحظة: تم تسليم المنتج محليًا للعميل',{exact:true}).waitFor();assert.equal(orderHistory.length,2);await page.getByText('إجمالي الصنف: ١١٠ ج.م',{exact:true}).waitFor();await page.screenshot({path:`qa/local-order-admin-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'التنبيهات',exact:true}).click();await page.getByText('طلب جديد يحتاج متابعة',{exact:true}).waitFor();await page.getByText('إشارات الاهتمام: 2 — محاولات الشراء خارج النطاق: 1',{exact:true}).waitFor();await page.getByRole('button',{name:'تمت المراجعة',exact:true}).click();assert.equal(await page.getByRole('button',{name:'تمت المراجعة',exact:true}).count(),0);
 await page.getByRole('button',{name:'الإرجاع والشكاوى',exact:true}).click();await page.getByText('طلب إرجاع منتج تجريبي للمراجعة',{exact:true}).waitFor();await page.getByLabel('الحالة',{exact:true}).selectOption('reviewing');await page.getByLabel('رد يظهر للعميل').fill('نراجع الطلب مع المورد');await page.getByRole('button',{name:'حفظ الرد والحالة',exact:true}).click();await page.getByText('حُفظ الرد؛ يراه العميل عند تحديث صفحة المتابعة.',{exact:true}).waitFor();assert.equal(support[0].status,'reviewing');assert.equal(support[0].customer_reply,'نراجع الطلب مع المورد');await page.screenshot({path:`qa/support-admin-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'مراجعة الربح',exact:true}).click();await page.getByLabel('الشحن المحصل من العميل').fill('50');await page.getByLabel('تكلفة الشحن الفعلية علينا').fill('50');await page.getByRole('button',{name:'احسب نتائج السيناريو',exact:true}).click();await page.getByText('المنتجات المفحوصة: 0',{exact:false}).waitFor();
 await page.getByRole('button',{name:'الأصناف'}).click();await page.getByRole('button',{name:'إضافة صنف'}).click();assert.equal(await page.getByLabel('مصدر المنتج').locator('option').count(),2);await page.getByLabel('مصدر المنتج').selectOption('supplier-test');
 await page.locator('.adminmodal .modalhead button').click();
 await page.evaluate(()=>sessionStorage.setItem('emad_last_invoice',JSON.stringify({id:'order-test',token:'test-invoice-token'})));
 await page.getByRole('button',{name:'متابعة طلبي والدفع',exact:true}).click();await page.getByText('رد المتجر: نراجع الطلب مع المورد',{exact:true}).waitFor();
 await page.getByLabel('نوع المساعدة').selectOption('complaint');await page.getByLabel('سبب الطلب والتفاصيل').fill('شكوى تجريبية عن تغليف المنتج');await page.getByRole('button',{name:'أرسل للمراجعة',exact:true}).click();await page.getByText('تم تسجيل طلب المساعدة للمراجعة؛ لم يتم إلغاء الطلب أو رد المال تلقائيًا.',{exact:true}).waitFor();assert.equal(support.length,2);assert.equal(support[1].kind,'complaint');await page.getByText('تم التسليم',{exact:true}).waitFor();await page.getByText('تم تأكيد الدفع',{exact:true}).waitFor();await page.screenshot({path:`qa/support-customer-${width}.png`,fullPage:true});await page.getByRole('button',{name:'إغلاق المتابعة',exact:true}).click();
 await page.getByLabel('محافظة الاهتمام',{exact:true}).selectOption('CAIRO');await page.getByRole('button',{name:'سجّل اهتمامك بالتوصيل',exact:true}).click();await page.getByText('تم تسجيل اهتمامك.',{exact:false}).waitFor();await page.getByRole('button',{name:'أضف للسلة',exact:true}).click();await page.locator('.cartbtn').click();await page.getByLabel('المحافظة',{exact:true}).waitFor();assert.deepEqual(await page.getByLabel('المحافظة',{exact:true}).locator('option').allTextContents(),['الفيوم']);assert.equal(await page.getByLabel('المحافظة',{exact:true}).inputValue(),'FAYOUM');assert.equal(await page.getByLabel('مدينة التوصيل',{exact:true}).locator('option').count(),6);await page.getByLabel('مدينة التوصيل',{exact:true}).selectOption('ITSA');assert.equal(await page.getByLabel('مدينة التوصيل',{exact:true}).inputValue(),'ITSA');await page.screenshot({path:`qa/fayoum-checkout-${width}.png`,fullPage:true});await page.locator('#cart .modalhead button').click();
 checkoutEnabled=false;await page.reload();await page.getByRole('button',{name:'أضف للسلة',exact:true}).click();await page.locator('.cartbtn').click();await page.getByText('الطلبات مغلقة أثناء التجهيز للإطلاق.',{exact:true}).waitFor();await page.getByLabel('مدينة التوصيل',{exact:true}).selectOption('ITSA');await page.locator('#cart input[type=checkbox]').check();assert.equal(await page.getByRole('button',{name:'تأكيد الطلب',exact:true}).isDisabled(),true);await page.locator('#cart .modalhead button').click();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await page.screenshot({path:`qa/supplier-admin-${width}.png`,fullPage:true});await context.close();
}console.log('Supplier directory UI passed on desktop and mobile');}finally{await browser.close();}
