import React,{useEffect,useState} from 'react';
const labels={pending:'جديد',new:'جديد',processing:'جارٍ التجهيز',confirmed:'مؤكد',fulfilled:'تم تجهيزه',shipped:'تم الشحن',delivered:'تم التسليم',cancelled:'ملغي',returned:'مرتجع',delivery_failed:'تعذر التسليم'};
const failures={order_changed:'تغيرت حالة الطلب؛ حدّث القائمة قبل إعادة المحاولة.',manual_cod_only:'هذا المسار للطلبات المحلية بالدفع عند الاستلام؛ راجع الدفع بصورة منفصلة.',fulfillment_requires_review:'للطلب إجراء شحن مسجل؛ راجع التنفيذ قبل تغيير حالته.',invalid_transition:'هذا الانتقال غير مسموح لحالة الطلب الحالية.',order_management_unavailable:'خدمة تحديث الطلبات غير متاحة؛ يلزم تجهيز الخدمة وقاعدة البيانات.'};
function OrderDetails({row,api,adminKey}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false);
 const load=async()=>{setOpen(true);setBusy(true);setError('');setData(null);try{const r=await fetch(api+'/admin/orders/'+encodeURIComponent(row.id)+'/details',{headers:{'x-admin-key':adminKey},cache:'no-store'});if(!r.ok)throw Error();setData(await r.json());}catch{setError('تعذر تحميل تفاصيل الطلب؛ أعد المحاولة قبل التجهيز.')}finally{setBusy(false)}};
 return <div className="order-details"><button type="button" onClick={load} disabled={busy}>{busy?'جارٍ تحميل التفاصيل…':'عرض المنتجات وسجل المتابعة'}</button>{open&&<><button type="button" onClick={()=>setOpen(false)}>إخفاء التفاصيل</button>{error&&<p role="alert">{error}</p>}{data&&<><h4>المنتجات المطلوبة</h4><p>الكميات وأسعار البيع محفوظة مع الطلب. الاسم والكود والمقاس واللون من الكتالوج الحالي؛ راجع أي تعديل لاحق قبل التجهيز.</p>{data.items.length?data.items.map(item=><div className="supplier-card" key={item.id}><h5>{item.title||'منتج يحتاج مراجعة'} — {item.sku||item.product_id}</h5><p>المقاس: {item.size||'غير مسجل'} — اللون: {item.color||'غير مسجل'}</p><p>الكمية: {item.quantity} — سعر القطعة وقت الطلب: {Number(item.unit_price).toLocaleString('ar-EG')} ج.م</p><p>إجمالي الصنف: {(Number(item.quantity)*Number(item.unit_price)).toLocaleString('ar-EG')} ج.م</p></div>):<p role="alert">لا توجد أصناف مسجلة؛ يحتاج الطلب مراجعة قبل التجهيز.</p>}<h4>آخر ٥٠ إجراء في سجل الإدارة</h4>{data.history.length?data.history.map(event=><div className="supplier-card" key={event.id}><p>{new Date(event.created_at).toLocaleString('ar-EG')}</p><p>{event.action==='manual_order_status_update'?'تحديث حالة الطلب':event.action==='order_status_update'?'تحديث حالة الطلب':'إجراء إداري مسجل'}: {labels[event.details?.from]||event.details?.from||'—'} ← {labels[event.details?.to||event.details?.status]||event.details?.to||event.details?.status||'—'}</p>{event.details?.note&&<p>الملاحظة: {event.details.note}</p>}</div>):<p>لا توجد إجراءات إدارية مسجلة لهذا الطلب.</p>}</>}</>}</div>;
}
function OrderAction({row,api,adminKey,onSaved}){
 const [status,setStatus]=useState(row.status==='pending'?'processing':'delivered'),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const save=async e=>{e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch(api+'/admin/orders/'+encodeURIComponent(row.id)+'/status',{method:'PATCH',headers:{'content-type':'application/json','x-admin-key':adminKey},body:JSON.stringify({expected_status:row.status,status,note})});const data=await r.json();if(!r.ok)throw Error(failures[data.error]||'تعذر حفظ الحالة؛ راجع الطلب وأعد المحاولة.');setNote('');onSaved(data);setMessage('تم حفظ الحالة وسجل المتابعة.');}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 return <><p>التحديث اليدوي للطلبات المحلية بالدفع عند الاستلام. تسجيل التسليم لا يؤكد تحصيل المال. الإلغاء قبل الشحن يعيد المخزون المحجوز؛ المرتجع يحتاج فحصًا منفصلًا.</p>{['pending','processing'].includes(row.status)&&<form onSubmit={save}><label>الحالة الجديدة<select value={status} onChange={e=>setStatus(e.target.value)}><option value={row.status==='pending'?'processing':'delivered'}>{row.status==='pending'?'جارٍ التجهيز':'تم التسليم'}</option><option value="cancelled">إلغاء قبل الشحن</option></select></label><label>ملاحظة المتابعة<textarea value={note} onChange={e=>setNote(e.target.value)} minLength={5} maxLength={2000} required placeholder="سبب التغيير وما تم التحقق منه"/></label><button disabled={busy}>{busy?'جارٍ الحفظ…':'حفظ حالة الطلب'}</button></form>}{message&&<p role="status">{message}</p>}</>;
}
export function AdminOrders({api,adminKey}){
 const [rows,setRows]=useState([]),[error,setError]=useState(''),[filter,setFilter]=useState('');
 const load=async()=>{setError('');try{const r=await fetch(api+'/admin/orders',{headers:{'x-admin-key':adminKey},cache:'no-store'});if(!r.ok)throw Error();setRows(await r.json());}catch{setError('تعذر تحميل الطلبات؛ راجع اتصال الخدمة.')}};
 useEffect(()=>{load()},[api,adminKey]);
 return <section><p>راجع الطلب والدفع والتوفر قبل إرسال بيانات التنفيذ للمورد أو شركة الشحن.</p><button className="tracking-link" onClick={load}>تحديث الطلبات</button><label>بحث برقم الطلب<input value={filter} onChange={e=>setFilter(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}{rows.filter(x=>String(x.order_number).includes(filter)).map(x=><article className="supplier-card" key={x.id}><h3>طلب {x.order_number}</h3><p>العميل: {x.customer_name} — {x.whatsapp_phone}</p><p>{x.address} — {x.governorate}</p><p>الإجمالي: {Number(x.total).toLocaleString('ar-EG')} ج.م</p><p>حالة الطلب: {labels[x.status]||x.status} — الدفع: {({unpaid:'لم يُدفع',pending:'بانتظار الدفع',paid:'مدفوع',failed:'تعذر الدفع',refunded:'تم الاسترداد'})[x.payment_status]||x.payment_status}</p><OrderDetails key={'details:'+x.status} row={x} api={api} adminKey={adminKey}/><OrderAction key={x.status} row={x} api={api} adminKey={adminKey} onSaved={saved=>setRows(current=>current.map(order=>order.id===saved.id?{...order,...saved}:order))}/></article>)}{!error&&!rows.length&&<p>لا توجد طلبات مسجلة.</p>}</section>;
}
