import React,{useEffect,useState,useRef} from 'react';
import {createAlertTracker} from './alert-notifier.js';
export function AlertCenter({api,adminKey}){
 const tracker=useRef(createAlertTracker()),audio=useRef(null),enabled=useRef(false);
 const [desktopMessage,setDesktopMessage]=useState(''),[desktopEnabled,setDesktopEnabled]=useState(false);
 const ring=()=>{try{const ctx=audio.current;if(!ctx||ctx.state!=='running')return;const tone=ctx.createOscillator(),gain=ctx.createGain();tone.frequency.value=740;gain.gain.setValueAtTime(.08,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.25);tone.connect(gain);gain.connect(ctx.destination);tone.start();tone.stop(ctx.currentTime+.25);}catch{}};
 const enableDesktop=async()=>{
  try{const Audio=window.AudioContext||window.webkitAudioContext;if(Audio){audio.current??=new Audio();await audio.current.resume();}enabled.current=true;setDesktopEnabled(true);ring();
   if('Notification' in window){const permission=await Notification.requestPermission();setDesktopMessage(permission==='granted'?'الصوت وإشعارات الكمبيوتر مفعّلان أثناء فتح مركز التنبيهات.':'الصوت مفعّل؛ إشعارات الكمبيوتر غير مسموحة في إعدادات المتصفح.');}
   else setDesktopMessage('الصوت مفعّل؛ هذا المتصفح لا يدعم إشعارات الكمبيوتر.');
  }catch{setDesktopMessage('تعذر تفعيل التنبيه على هذا الجهاز. تظل قائمة التنبيهات متاحة.');}
 };
 useEffect(()=>()=>{audio.current?.close().catch(()=>{});},[]);
 const [demand,setDemand]=useState([]),[demandUnavailable,setDemandUnavailable]=useState(false),[rows,setRows]=useState([]),[error,setError]=useState(''),[ack,setAck]=useState(()=>{try{return JSON.parse(localStorage.getItem('otlob_alerts_reviewed'))||[]}catch{return []}}),[updated,setUpdated]=useState(null);
 useEffect(()=>{let stopped=false;const controller=new AbortController();const refresh=async()=>{try{const r=await fetch(api+'/admin/alerts',{headers:{'x-admin-key':adminKey},cache:'no-store',signal:controller.signal});if(!r.ok)throw Error();const data=await r.json();if(!stopped){const fresh=tracker.current(data.alerts||[]);if(enabled.current&&fresh.length){ring();if('Notification' in window&&Notification.permission==='granted'){try{new Notification('اطلب ووفر — تنبيه جديد',{body:'يوجد تحديث يحتاج مراجعتك داخل الإدارة.',tag:'otlob-operational-alert'});}catch{setDesktopMessage('إشعارات الكمبيوتر غير متاحة؛ راجع قائمة التنبيهات.');}}}setRows(data.alerts||[]);setDemand(data.deliveryDemand||[]);setDemandUnavailable(!!data.deliveryDemandUnavailable);setUpdated(new Date());setError('')}}catch(e){if(!stopped&&e.name!=='AbortError')setError('تعذر تحديث التنبيهات. راجع الاتصال ولا تعتمد على القائمة القديمة.')}};refresh();const timer=setInterval(refresh,30000);return()=>{stopped=true;controller.abort();clearInterval(timer)}},[api,adminKey]);
 const review=id=>{const next=[...new Set([...ack,id])].slice(-500);setAck(next);localStorage.setItem('otlob_alerts_reviewed',JSON.stringify(next))};
 const unread=rows.filter(x=>!ack.includes(x.id));
 return <section className="alert-center"><button type="button" className="checkout" onClick={enableDesktop}>{desktopEnabled?'اختبار الصوت وإشعارات الكمبيوتر':'تفعيل الصوت وإشعارات الكمبيوتر'}</button>{desktopMessage&&<p role="status">{desktopMessage}</p>}<p>أبقِ مركز التنبيهات مفتوحًا. هذه الإشعارات لا تعمل بعد إغلاق الموقع، وقد يؤخرها المتصفح في الخلفية.</p><h3>مركز التنبيهات — {unread.length} تحتاج مراجعتك</h3><p>التحديث كل 30 ثانية أثناء فتح المركز. تعليم التنبيه كمُراجع محفوظ على هذا الجهاز ولا يغير حالة الطلب.</p>{updated&&<small>آخر تحديث: {updated.toLocaleTimeString('ar-EG')}</small>}{error&&<p role="alert">{error}</p>}{!error&&!unread.length&&<p>لا توجد تنبيهات جديدة ضمن أحدث السجلات المفحوصة.</p>}<h3>اهتمام المحافظات — آخر 30 يومًا</h3><p>الإشارات ومحاولات الشراء خارج النطاق تساعد في قرار التوسع؛ ليست مبيعات ولا عدد عملاء فريدين.</p>{demandUnavailable?<p role="alert">تعذر تحميل إحصاء المحافظات.</p>:!demand.length?<p>لم تسجل إشارات اهتمام خلال هذه الفترة.</p>:demand.map(r=><article className="supplier-card" key={r.region}><h4>{({FAYOUM:'الفيوم',CAIRO:'القاهرة',GIZA:'الجيزة',ALEXANDRIA:'الإسكندرية',DELTA_CANAL:'الدلتا والقناة',UPPER_EGYPT:'الصعيد'})[r.region]||r.region}</h4><p>إشارات الاهتمام: {r.interest_count} — محاولات الشراء خارج النطاق: {r.blocked_count}</p></article>)}{unread.map(a=><article className="supplier-card" key={a.id}><h4>{a.title}</h4><p>{a.detail}</p><small>{a.at?new Date(a.at).toLocaleString('ar-EG'):''}</small><button className="checkout" onClick={()=>review(a.id)}>تمت المراجعة</button></article>)}</section>;
}
