import React,{useState} from 'react';
import {reviewCatalogProduct} from '../../../shared/catalog-review.js';
export function CatalogReview({api,adminKey}) {
 const [rows,setRows]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const submit=async e=>{e.preventDefault();setBusy(true);setRows(null);setError('');const f=new FormData(e.currentTarget);const settings=Object.fromEntries(['rate','fixed','taxRate','shippingCharge','shippingCost'].map(k=>[k,Number(f.get(k))]));settings.rate/=100;settings.taxRate/=100;
 try{const r=await fetch(api+'/admin/products',{headers:{'x-admin-key':adminKey},cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();setRows(data.map(p=>({...p,review:reviewCatalogProduct(p,settings)})));}catch{setError('تعذر تحميل الكتالوج للمراجعة.')}finally{setBusy(false);}
 };
 return <section><h3>مراجعة الربح قبل الإطلاق</h3><p>محاكاة لبيع قطعة واحدة في طلب مستقل. أدخل الرسوم والشحن الفعليين. النتيجة لا تؤكد أقل سعر بالسوق ولا تغيّر السعر أو التوفر. اجتياز السيناريو لا يعني اعتماد المنتج للبيع.</p><form onSubmit={submit}><label>رسوم الدفع النسبية %<input name="rate" type="number" min="0" max="99" step=".001" defaultValue="2.75" required/></label><label>رسوم الدفع الثابتة للطلب<input name="fixed" type="number" min="0" step=".01" defaultValue="3" required/></label><label>ضريبة على رسوم الدفع % — تحقق من عقدك<input name="taxRate" type="number" min="0" step=".01" defaultValue="0" required/></label><label>الشحن المحصل من العميل<input name="shippingCharge" type="number" min="0" step=".01" required/></label><label>تكلفة الشحن الفعلية علينا<input name="shippingCost" type="number" min="0" step=".01" required/></label><button className="checkout" disabled={busy}>{busy?'جاري المراجعة…':'احسب نتائج السيناريو'}</button></form>{error&&<p role="alert">{error}</p>}{rows&&<><p>المنتجات المفحوصة: {rows.length} — دون الحد المطلوب: {rows.filter(p=>p.review.status==='below_floor').length}</p>{rows.map(p=><div className="line" key={p.id}><span>{p.title_ar}<small className="comparison-time">{p.available?'ظاهر بالكتالوج':'محجوب حاليًا'}</small></span><span><b>{p.review.status==='passes_scenario'?'يحقق الحد في هذا السيناريو':p.review.status==='below_floor'?'يحتاج تعديلًا أو حجبًا':'بيانات غير صالحة'}</b>{p.review.profitRate!=null&&<small className="comparison-time">ربح بعد الاحتياطي: {(p.review.profitRate*100).toFixed(2)}% — رسوم الدفع: {p.review.paymentFee.toFixed(2)} ج.م</small>}</span></div>)}</>}</section>;
}
