import React,{useState} from 'react';
import {FullPageDialog} from './full-page-dialog.jsx';
export function LaunchPreview({profile,image}) {
 const [details,setDetails]=useState(false);
 const phone=String(profile?.phone||'').replace(/[^\d+]/g,'');
 return <section className="launch-preview" aria-labelledby="launch-heading" id="launch-product">
 <div className="launch-intro"><span className="launch-label">قريبًا في الفيوم</span><h2 id="launch-heading">اطلب ووفر… بنجهّز أول اختياراتنا ليك</h2><p>البداية من مخزون محلنا، ومع التوسع نضيف منتجات من موردين بعد مراجعة السعر والتوفر. الأقسام كلها موجودة، والمنتجات هتزيد بالتدريج.</p><p className="notice">الطلبات الإلكترونية لم تُفتح بعد. الاستفسار بالتليفون لا ينشئ طلبًا أو يحجز قطعة.</p></div>
 <article className="launch-product">{image&&<img src={image} alt="الصورة الأصلية للكوتشي الرجالي الأسود TIMO" width="640" height="480"/>}<div><small>من مخزون محلنا — عرض تمهيدي</small><h3>كوتشي رجالي TIMO — أسود</h3><p>المقاسات من 41 إلى 45. نراجع توفر مقاسك عند التواصل قبل تأكيد أي بيع.</p><div className="launch-price"><strong>280 ج.م</strong><span>التوصيل داخل النطاق: 35 ج.م</span><b>الإجمالي مع التوصيل: 315 ج.م</b></div><p>التغطية عند بدء التوصيل: مدينة الفيوم ومدن سنورس وطامية وإطسا وأبشواي. مركز يوسف الصديق والقرى خارج النطاق الحالي.</p><button onClick={()=>setDetails(true)}>شوف الصورة والتفاصيل</button>{phone&&<a className="launch-call" href={'tel:'+phone}>اتصل للاستفسار عن المنتج</a>}</div></article>
 <div className="launch-contact"><h3>عميل أو تاجر؟ يسعدنا تواصلك</h3><p>لو عندك منتج جيد بسعر مناسب، أو فكرة تفيد المتجر، تواصل معنا. اتفاق التوريد وتوفر البيع بالقطعة يتراجعان قبل إضافة المنتج.</p>{profile?.address&&<p>المحل: {profile.address}</p>}{profile?.hours&&<p>المواعيد: {profile.hours}</p>}{phone&&<a href={'tel:'+phone}>رقم المحل: <b dir="ltr">{phone}</b></a>}</div>
 {details&&<FullPageDialog className="modal launch-details" label="عرض المنتج قبل الافتتاح" onClose={()=>setDetails(false)}><div className="modalhead"><h2>كوتشي رجالي TIMO — أسود</h2><button aria-label="إغلاق عرض المنتج" onClick={()=>setDetails(false)}>العودة للمتجر ×</button></div>{image&&<img src={image} alt="الصورة الأصلية للكوتشي الرجالي الأسود" width="640" height="480"/>}<p>سعر القطعة 280 ج.م. التوصيل 35 ج.م؛ الإجمالي 315 ج.م داخل نطاق التوصيل. المقاسات 41–45، والتوفر يؤكد عند التواصل.</p><p>هذه معاينة قبل الافتتاح؛ لا تحجز مخزونًا ولا تؤكد طلبًا. لا تتوفر حاليًا مقارنة موثقة لسعر هذا الموديل لدى المتاجر الأخرى.</p>{phone&&<a className="launch-call" href={'tel:'+phone}>اتصل بالمحل للاستفسار</a>}</FullPageDialog>}
 </section>;
}
