import {DeliveryInterest} from './delivery-interest.jsx';
import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ShoppingBag,LockKeyhole,Trash2,Plus,Minus,ShieldCheck,Zap,Settings,PackagePlus,BarChart3,Power,Sun,Moon,Search,Download} from 'lucide-react';
import './styles.css';
import {filterCatalog,productChoices} from './catalog.js';
import {ProductPage} from './product-page.jsx';
import {FullPageDialog} from './full-page-dialog.jsx';
import {AdminOrders} from './admin-orders.jsx';
import {StoreInfo} from './store-info.jsx';
import {customerAuth} from './auth.js';
import {OrderTracking} from './order-tracking.jsx';
import {SupplierDirectory} from './suppliers.jsx';
import {AlertCenter} from './alerts.jsx';
import {ProductFacts} from './product-facts.jsx';
import {LinkSearch} from './link-search.jsx';
import {CatalogReview} from './catalog-review.jsx';
import {SupportRequests} from './support-requests.jsx';
const asset=(path)=>import.meta.env.BASE_URL+path;
const safeSource=url=>{try{const u=new URL(url);return u.protocol==='https:'?u.href:null}catch{return null}};
const storeName={amazon:'أمازون',noon:'نون',btech:'بي تك'};

function stored(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
const API=import.meta.env.VITE_API_URL||'';
const shoeCats=[['footwear-men','رجالي'],['footwear-women','حريمي'],['footwear-kids','أطفال'],['slippers','شباشب']];
const isShoe=p=>['shoes',...shoeCats.map(([id])=>id)].includes(p.cat||p.category_slug);
const cats=[['all','الكل'],['shoes','الأحذية'],['footwear-men','أحذية رجالي'],['footwear-women','أحذية حريمي'],['footwear-kids','أحذية أطفال'],['slippers','شباشب'],['electrical','أجهزة وأدوات كهربائية'],['home','أدوات منزلية ومطبخ'],['electronics','موبايلات وإلكترونيات'],['accessories','ساعات وإكسسوارات'],['health','الصحة والجمال'],['gaming','ألعاب وترفيه'],['school-supplies','أدوات ومستلزمات مدرسية']];
const demo=[
{id:'EM-101',sku:'EM-101',title_ar:'خلاط كهربائي 1000 وات',cat:'electrical',retail_price:899,image_url:'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=700&q=80'},
{id:'EM-102',sku:'EM-102',title_ar:'طقم أواني جرانيت 10 قطع',cat:'home',retail_price:1249,image_url:'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=700&q=80'},
{id:'EM-103',sku:'EM-103',title_ar:'سماعة بلوتوث لاسلكية',cat:'electronics',retail_price:749,image_url:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=700&q=80'},
{id:'EM-104',sku:'EM-104',title_ar:'ساعة ذكية رياضية',cat:'accessories',retail_price:1099,image_url:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=700&q=80'}];
const shipping={FAYOUM:35,CAIRO:50,GIZA:50,ALEXANDRIA:60,DELTA_CANAL:65,UPPER_EGYPT:75};
const govLabels={FAYOUM:'الفيوم',CAIRO:'القاهرة',GIZA:'الجيزة',ALEXANDRIA:'الإسكندرية',DELTA_CANAL:'الدلتا ومدن القناة',UPPER_EGYPT:'محافظات الصعيد'};
function Logo(){return <div className="brand"><img className="brand-mark" src={asset('brand-v2.svg')} alt="" width="48" height="48"/><div><b>اطلب ووفر</b><small>إحنا ندوّر ونقارن… وإنت تختار وتوفّر.</small></div></div>}
function App(){
 const [profile,setProfile]=useState(null),[sort,setSort]=useState('default'),[size,setSize]=useState(''),[color,setColor]=useState(''),[availableOnly,setAvailableOnly]=useState(false),[minPrice,setMinPrice]=useState(''),[maxPrice,setMaxPrice]=useState('');
 useEffect(()=>{if(API)fetch(API+'/store-profile').then(r=>r.ok?r.json():null).then(setProfile).catch(()=>{})},[]);

 const [favorites,setFavorites]=useState(()=>{const x=stored('otlob_favorites',[]);return Array.isArray(x)?x.filter(id=>typeof id==='string').slice(0,500):[]}),[favoritesOnly,setFavoritesOnly]=useState(false);
 useEffect(()=>{try{localStorage.setItem('otlob_favorites',JSON.stringify(favorites))}catch{}},[favorites]);
 const toggleFavorite=id=>setFavorites(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids.slice(-499),id]);
 const [suppliers,setSuppliers]=useState([]);
 const loadSuppliers=async()=>{const r=await fetch(API+'/admin/suppliers',{headers:{'x-admin-key':adminKey}});if(!r.ok)throw Error('دليل الموردين غير متاح قبل تطبيق التحديث');setSuppliers(await r.json())};
 const [externalResults,setExternalResults]=useState(null),[externalBusy,setExternalBusy]=useState(false),[externalMessage,setExternalMessage]=useState('');
 const externalSearch=async()=>{setExternalBusy(true);setExternalResults(null);setExternalMessage('');try{if(!API)throw Error();const r=await fetch(API+'/catalog/search?q='+encodeURIComponent(query));if(!r.ok)throw Error();const data=await r.json();setExternalResults(data);if(!data.quotes.length)setExternalMessage('لا يتوفر عرض مناسب حاليًا من المصادر المتصلة.');}catch{setExternalMessage('البحث الخارجي غير متاح الآن؛ يحتاج ربط مصادر الأسعار والموردين.')}finally{setExternalBusy(false)}};
 const [tracking,setTracking]=useState(()=>new URLSearchParams(location.search).has('payment_return')||location.hash.startsWith('#track=')),[invoice,setInvoice]=useState(null),[categories,setCategories]=useState([]);
 useEffect(()=>{if(API)fetch(API+'/categories').then(r=>r.json()).then(x=>Array.isArray(x)&&setCategories(x)).catch(()=>{})},[]);
 const showInvoice=async()=>{try{const saved=JSON.parse(sessionStorage.getItem('emad_last_invoice'));if(!saved)return;const r=await fetch(API+'/orders/'+saved.id+'/invoice',{headers:{Authorization:'Bearer invoice:'+saved.token}});if(!r.ok)throw new Error('تعذر تحميل الفاتورة');setInvoice(await r.json())}catch(e){setMsg(e.message)}};
 const [policy,setPolicy]=useState(null),[policyAccepted,setPolicyAccepted]=useState(false);
 useEffect(()=>{if(API)fetch(API+'/policies').then(r=>r.json()).then(setPolicy).catch(()=>{})},[]);
 const [deliveryGovernorates,setDeliveryGovernorates]=useState(API?[]:Object.keys(shipping));
 const [session,setSession]=useState(null),[accountOpen,setAccountOpen]=useState(false),[authMessage,setAuthMessage]=useState(''),[onlineReady,setOnlineReady]=useState(false);
 useEffect(()=>{if(!customerAuth)return;customerAuth.auth.getSession().then(({data})=>setSession(data.session));const {data}=customerAuth.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(API)fetch(API+'/capabilities').then(r=>{if(!r.ok)throw Error();return r.json()}).then(x=>{setOnlineReady(x.onlinePayment===true);const regions=Array.isArray(x.deliveryGovernorates)?x.deliveryGovernorates.filter(code=>Object.hasOwn(shipping,code)):Object.keys(shipping);setDeliveryGovernorates(regions);if(regions.length)setGov(regions[0])}).catch(()=>{})},[]);
 const accountAction=async(e,register=false)=>{e.preventDefault();if(!customerAuth)return;const f=new FormData(e.currentTarget);const credentials={email:String(f.get('email')),password:String(f.get('password'))};const result=register?await customerAuth.auth.signUp(credentials):await customerAuth.auth.signInWithPassword(credentials);setAuthMessage(result.error?'تعذر إتمام العملية. راجع بياناتك وحاول مرة أخرى.':register?'تم التسجيل. تحقق من بريدك لتأكيد الحساب.':'تم تسجيل الدخول');if(!result.error&&!register)setAccountOpen(false)};
 const [theme,setTheme]=useState(()=>stored('emad_theme','dark')),[query,setQuery]=useState(''),[comparison,setComparison]=useState([]),[comparisonError,setComparisonError]=useState(''),[loading,setLoading]=useState(!!API),[catalogError,setCatalogError]=useState(''),[draft,setDraft]=useState(null),[adminProducts,setAdminProducts]=useState([]),[installPrompt,setInstallPrompt]=useState(null);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('emad_theme',JSON.stringify(theme))},[theme]);
 useEffect(()=>{localStorage.removeItem('emad_admin_key');const h=e=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener('beforeinstallprompt',h);return()=>window.removeEventListener('beforeinstallprompt',h)},[]);
 const [products,setProducts]=useState(demo),[cat,setCat]=useState('all'),[cart,setCart]=useState(()=>stored('emad_cart',[])),[compare,setCompare]=useState(null),[admin,setAdmin]=useState(false),[adminKey,setAdminKey]=useState(''),[authed,setAuthed]=useState(false),[tab,setTab]=useState('kpi'),[kpis,setKpis]=useState({grossSales:0,totalOrders:0}),[gov,setGov]=useState('CAIRO'),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>{const lock=admin||compare;document.body.style.overflow=lock?'hidden':'';return()=>{document.body.style.overflow=''}},[admin,compare]);
 useEffect(()=>{if(authed)loadSuppliers().catch(e=>setMsg(e.message))},[authed]);
 useEffect(()=>{const id=new URLSearchParams(location.search).get('product');if(id){const p=products.find(p=>p.id===id);if(p)setCompare(p)}},[products]);
 useEffect(()=>{localStorage.setItem('emad_cart',JSON.stringify(cart))},[cart]);
 useEffect(()=>{if(!API)return;fetch(API+'/products').then(async r=>{if(!r.ok)throw new Error('تعذر تحميل المنتجات');return r.json()}).then(setProducts).catch(()=>{setProducts([]);setCatalogError('تعذر الاتصال بالمتجر. حاول تحديث الصفحة.')}).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(!compare)return;setComparison([]);setComparisonError('');if(!API){setComparisonError('المقارنة تحتاج اتصال المتجر؛ المنتجات المعروضة للتجربة.');return}const c=new AbortController();fetch(API+'/products/'+compare.id+'/compare',{signal:c.signal}).then(async r=>{if(!r.ok)throw new Error('تعذر تحميل المقارنة');return r.json()}).then(setComparison).catch(e=>{if(e.name!=='AbortError')setComparisonError('تعذر تحميل أسعار المنافسين الآن.')});return()=>c.abort()},[compare]);
 const loadAdminProducts=async()=>{try{const r=await fetch(API+'/admin/products',{headers:{'x-admin-key':adminKey}});if(!r.ok)throw new Error('تعذر تحميل الأصناف');setAdminProducts(await r.json());setTab('products')}catch(e){setMsg(e.message)}};
 const saveProduct=async e=>{e.preventDefault();setBusy(true);try{const f=new FormData(e.currentTarget),data=Object.fromEntries(f);data.specifications={...JSON.parse(data.specifications||'{}'),model_key:String(f.get('model_key')||'').trim(),color:String(f.get('color')||'').trim(),size:String(f.get('size')||'').trim(),gallery_urls:String(f.get('gallery_urls')||'').trim()};for(const key of ['model_key','color','size','gallery_urls'])delete data[key];data.category_id=data.category_id||null;data.supplier_id=data.supplier_id||null;data.supplier_cost=Number(data.supplier_cost);data.retail_price=Number(data.retail_price);data.available=data.available==='on';data.stock_quantity=data.stock_quantity===''?null:Number(data.stock_quantity);const r=await fetch(API+'/admin/products'+(draft.id?'/'+draft.id:''),{method:draft.id?'PATCH':'POST',headers:{'content-type':'application/json','x-admin-key':adminKey},body:JSON.stringify(data)});if(!r.ok)throw new Error('تعذر حفظ المنتج. تحقق من البيانات وحد الربح.');setDraft(null);await loadAdminProducts();const list=await fetch(API+'/products');if(list.ok)setProducts(await list.json());setMsg('تم حفظ المنتج')}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 const filtered=useMemo(()=>filterCatalog(cat==='shoes'?products.filter(isShoe):products,{query,category:cat==='shoes'?'all':cat,size,color,availability:availableOnly,sort,min:minPrice,max:maxPrice,favorites:favoritesOnly?favorites:null}),[products,cat,query,favorites,favoritesOnly,size,color,availableOnly,sort,minPrice,maxPrice]);
 const catalogSizes=[...new Set(products.map(p=>p.specifications?.size).filter(x=>x!=null))].sort((a,b)=>Number(a)-Number(b));
 const catalogColors=[...new Set(products.map(p=>p.specifications?.color).filter(Boolean))];
 const items=cart.map(x=>products.find(p=>p.id===x.id)?{...products.find(p=>p.id===x.id),qty:x.qty}:null).filter(Boolean);
 const subtotal=items.reduce((s,p)=>s+Number(p.retail_price)*p.qty,0),total=subtotal+(items.length?shipping[gov]:0);
 const openAdmin=()=>{setAdmin(true);setMsg('')};
 const login=async()=>{if(!adminKey.trim()){setMsg('أدخل مفتاح الإدارة');return;}if(!API){setMsg('API غير مهيأ');return;}setBusy(true);setMsg('');try{const r=await fetch(API+'/admin/kpis',{headers:{'x-admin-key':adminKey}});if(!r.ok)throw new Error('مفتاح الإدارة غير صحيح');const data=await r.json();setKpis(data);setAuthed(true);}catch(err){setAuthed(false);localStorage.removeItem('emad_admin_key');setMsg(err.message||'فشل تسجيل الدخول');}finally{setBusy(false);}};
 const add=p=>{if(productChoices(p,products).length>1&&!compare){setCompare(p);return;}setCart(c=>{const limit=Math.min(100,p.stock_quantity??100);if(limit<1)return c;return c.some(x=>x.id===p.id)?c.map(x=>x.id===p.id?{...x,qty:Math.min(limit,x.qty+1)}:x):[...c,{id:p.id,qty:1}];});setMsg('تمت إضافة الاختيار إلى السلة');};
 const submit=async e=>{e.preventDefault();setBusy(true);setMsg('');const f=new FormData(e.currentTarget);const payload={customer_name:f.get('name'),whatsapp_phone:f.get('phone'),governorate:gov,address:f.get('address'),payment_method:f.get('payment'),items:items.map(x=>({product_id:x.id,quantity:x.qty})),policy_version:policy?.version,policy_accepted:policyAccepted};try{if(!API)throw new Error('المتجر غير متصل بعد');if(!deliveryGovernorates.includes(gov))throw new Error('التوصيل غير متاح للمحافظة المختارة حاليًا');if(payload.payment_method==='wallet'&&!session)throw new Error('سجّل الدخول أولًا للدفع الإلكتروني');const fingerprint=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(payload))))).map(x=>x.toString(16).padStart(2,'0')).join('');let intent=stored('emad_order_intent',null);if(!intent||intent.fingerprint!==fingerprint){intent={fingerprint,key:crypto.randomUUID()};localStorage.setItem('emad_order_intent',JSON.stringify(intent))}const idem=intent.key;const r=await fetch(API+'/orders',{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':idem,...(session?{Authorization:'Bearer '+session.access_token}:{})},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error==='delivery_region_unavailable'?'التوصيل غير متاح للمحافظة المختارة حاليًا':j.error||'فشل الطلب');sessionStorage.setItem('emad_last_invoice',JSON.stringify({id:j.id,token:j.invoice_token}));if(payload.payment_method==='wallet'){if(!session)throw new Error('سجّل الدخول أولًا للدفع الإلكتروني');sessionStorage.setItem('emad_pending_payment',j.id);const pay=await fetch(API+'/payments/paymob/intention',{method:'POST',headers:{'content-type':'application/json',Authorization:'Bearer '+session.access_token},body:JSON.stringify({orderId:j.id})});const checkout=await pay.json();if(!pay.ok||!checkout.checkout_url)throw new Error('تم حفظ الطلب، لكن تعذر بدء الدفع. أعد المحاولة بنفس البيانات.');location.assign(checkout.checkout_url);return}setTracking(true);setMsg(`تم إنشاء الطلب ${j.order_number} بإجمالي ${Number(j.total).toLocaleString('ar-EG')} ج.م`);localStorage.removeItem('emad_order_intent');setCart([]);}catch(err){setMsg(err.message)}finally{setBusy(false)}};
 return <div className="app"><div className="ticker"><Zap size={16}/> اختيارات بعناية • مقارنة أسعار متاحة • {deliveryGovernorates.length===1?'التوصيل حاليًا داخل '+govLabels[deliveryGovernorates[0]]:'التوصيل حسب المحافظات المتاحة عند الطلب'}</div>
 <header><Logo/><nav className="main-categories" aria-label="أقسام المتجر">{cats.filter(([id])=>!shoeCats.some(([child])=>child===id)).map(([id,n])=><button key={id} className={cat===id||(id==='shoes'&&shoeCats.some(([child])=>child===cat))?'active':''} onClick={()=>setCat(id)}>{n}<em>{id==='all'?products.length:id==='shoes'?products.filter(isShoe).length:products.filter(p=>(p.cat||p.category_slug)===id).length}</em></button>)}</nav><div className="head-actions">{customerAuth&&<button className="admin account-toggle" onClick={()=>setAccountOpen(true)}>{session?'حسابي':'دخول العميل'}</button>}<button className="admin theme-toggle" aria-label="تبديل السمة" onClick={()=>setTheme(t=>t==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button>{installPrompt&&<button className="admin" onClick={async()=>{await installPrompt.prompt();setInstallPrompt(null)}} aria-label="تثبيت التطبيق"><Download size={18}/></button>}<button className="admin" aria-label="دخول الإدارة" onClick={openAdmin}><LockKeyhole size={15}/> دخول الإدارة</button><button className="cartbtn" onClick={()=>document.getElementById('cart').showModal()}><ShoppingBag size={20}/><span>{cart.reduce((s,x)=>s+x.qty,0)}</span></button></div></header>
 <main><section className="hero"><div><div className="eyebrow"><ShieldCheck size={16}/> تسوق بثقة</div><h1>سوق أذكى.<br/><span>سعر أقل.</span> بدون تنازل.</h1><p>منتجات لحياتك اليومية، وأسعار مدروسة. تصفح، قارن، واطلب بخطوات بسيطة.</p></div><div className="hero-card"><div className="bolt"><Zap/></div><b>تسعير تنافسي</b><strong className="promise-title">اعرف قبل ما تطلب</strong><small>المصدر والتوفر والشحن ومقارنة موثوقة عند توفرها</small></div></section>
 {(cat==='shoes'||shoeCats.some(([id])=>id===cat))&&<nav className="shoe-subcategories" aria-label="أقسام الأحذية">{[['shoes','كل الأحذية'],...shoeCats].map(([id,label])=><button key={id} className={cat===id?'active':''} onClick={()=>setCat(id)}>{label}</button>)}</nav>}<section className="catalog-tools"><div><span className="eyebrow">اختيارات المتجر</span><h2>اكتشف ما يناسبك</h2></div><label className="search"><Search size={20}/><input aria-label="البحث عن منتج" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن منتج أو كود…"/></label></section>{!API&&<p className="catalog-notice">نسخة معاينة — المنتجات والأسعار تجريبية حتى ربط المتجر.</p>}{loading&&<p className="catalog-notice" role="status">جاري تحميل المنتجات…</p>}{catalogError&&<p className="catalog-notice" role="alert">{catalogError}</p>}{!loading&&!catalogError&&!filtered.length&&<p className="catalog-notice">{cat!=='all'&&!(cat==='shoes'&&products.some(isShoe))&&!products.some(p=>(p.cat||p.category_slug)===cat)?'هذا القسم موجود بالمتجر؛ لم تُضف له منتجات متاحة بعد.':'لا توجد منتجات مطابقة.'}</p>}
 <section className="external-search"><h3>بتدور على منتج مش موجود؟</h3><p>اكتب اسم المنتج ورقم الموديل، ثم افحص المصادر المتصلة. العروض الجديدة تحتاج تأكيد التوفر والسعر قبل الطلب.</p><button className="checkout" disabled={externalBusy||query.trim().length<2} onClick={externalSearch}>{externalBusy?'جاري البحث…':'ابحث خارج المتجر'}</button>{externalMessage&&<p role="status">{externalMessage}</p>}{externalResults&&<><p>مصادر فُحصت: {externalResults.sourcesChecked} — تعذر الاتصال بـ: {externalResults.sourcesUnavailable}</p>{externalResults.quotes.map(q=><div className="line" key={q.productKey}><span>{q.title||q.productKey}</span><b>{q.status==='preview'?Number(q.price).toLocaleString('ar-EG')+' ج.م شامل شحن المورد — تقديري':q.status==='margin_unavailable'?'لا يتوفر سعر يحقق شروط التوفير والربح':'يحتاج موردًا معتمدًا'}</b></div>)}</>}</section>
 <LinkSearch api={API}/><section className="catalog-filters" aria-label="تصفية المنتجات"><label>المقاس<select value={size} onChange={e=>setSize(e.target.value)}><option value="">كل المقاسات</option>{catalogSizes.map(x=><option key={x}>{x}</option>)}</select></label><label>اللون<select value={color} onChange={e=>setColor(e.target.value)}><option value="">كل الألوان</option>{catalogColors.map(x=><option key={x}>{x}</option>)}</select></label><label>السعر من<input type="number" min="0" value={minPrice} onChange={e=>setMinPrice(e.target.value)}/></label><label>إلى<input type="number" min="0" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)}/></label><label>الترتيب<select value={sort} onChange={e=>setSort(e.target.value)}><option value="default">ترتيب المتجر</option><option value="price-asc">السعر: الأقل أولًا</option><option value="price-desc">السعر: الأعلى أولًا</option><option value="name">الاسم</option></select></label><label className="check-filter"><input type="checkbox" checked={availableOnly} onChange={e=>setAvailableOnly(e.target.checked)}/> مخزون مؤكد فقط</label><button onClick={()=>{setSize('');setColor('');setMinPrice('');setMaxPrice('');setAvailableOnly(false);setSort('default');setQuery('')}}>مسح الفلاتر</button><small>{filtered.length} اختيار مطابق</small></section><div className="favorite-tools"><button aria-pressed={favoritesOnly} onClick={()=>setFavoritesOnly(x=>!x)}>{favoritesOnly?'عرض كل المنتجات':'المفضلة'} ({favorites.length})</button><small>تُحفظ المفضلة على هذا الجهاز.</small></div><section className="grid">{filtered.filter((p,i,list)=>!p.specifications?.model_key||list.findIndex(x=>x.specifications?.model_key===p.specifications.model_key)===i).map(p=><article className="product" key={p.id}><div className="pic"><img src={p.image_url} alt={p.title_ar} loading="lazy" onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src=asset('icon.svg');e.currentTarget.classList.add('fallback-image')}}/><button className="compare" onClick={()=>setCompare(p)}>فحص ومقارنة</button></div><div className="pbody"><button className="favorite-button" aria-label={(favorites.includes(p.id)?'إزالة من المفضلة: ':'حفظ في المفضلة: ')+p.title_ar} aria-pressed={favorites.includes(p.id)} onClick={()=>toggleFavorite(p.id)}>{favorites.includes(p.id)?'♥ محفوظ':'♡ احفظ المنتج'}</button><small>{cats.find(x=>x[0]===(p.cat||p.category_slug))?.[1]||'منتج'}</small><h3>{p.title_ar}</h3><div className="price"><strong>{Number(p.retail_price).toLocaleString('ar-EG')} ج.م</strong></div><button className="add" disabled={p.stock_quantity===0} onClick={()=>productChoices(p,products).length>1?setCompare(p):add(p)}><ShoppingBag size={17}/> {p.stock_quantity===0?'نفد المخزون':productChoices(p,products).length>1?'اختر اللون والمقاس':'أضف للسلة'}</button></div></article>)}</section><StoreInfo profile={profile} policy={policy}/></main>
 <dialog id="cart" className="modal"><div className="modalhead"><h2>سلة الشراء</h2><button onClick={()=>document.getElementById('cart').close()}>×</button></div>{items.length===0?<div className="empty">السلة فارغة{msg&&<p role="status">{msg}</p>}{sessionStorage.getItem('emad_last_invoice')&&<button className="checkout" onClick={showInvoice}>عرض آخر فاتورة</button>}</div>:<><div className="cartitems">{items.map(p=><div className="cartrow" key={p.id}><img src={p.image_url} alt={p.title_ar} loading="lazy" onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src=asset('icon.svg');e.currentTarget.classList.add('fallback-image')}}/><div><b>{p.title_ar}</b><small>{[p.specifications?.color,p.specifications?.size].filter(Boolean).join(" — ")}</small><small>{Number(p.retail_price).toLocaleString('ar-EG')} ج.م</small></div><div className="qty"><button onClick={()=>setCart(c=>c.map(x=>x.id===p.id?{...x,qty:Math.max(1,x.qty-1)}:x))}><Minus size={14}/></button>{p.qty}<button onClick={()=>add(p)}><Plus size={14}/></button><button onClick={()=>setCart(c=>c.filter(x=>x.id!==p.id))}><Trash2 size={15}/></button></div></div>)}</div><form onSubmit={submit}><p className="notice">يمكنك الطلب بالدفع عند الاستلام دون إنشاء حساب. راجع الاختيارات والتكلفة كاملة قبل التأكيد.</p>{API&&!deliveryGovernorates.length&&<p className="notice">نطاق التوصيل غير متاح حاليًا. حاول تحديث الصفحة قبل تأكيد الطلب.</p>}<label>المحافظة<select aria-label="المحافظة" disabled={!deliveryGovernorates.length} value={gov} onChange={e=>setGov(e.target.value)}>{deliveryGovernorates.map(x=><option value={x} key={x}>{govLabels[x]}</option>)}</select></label><input name="name" required placeholder="اسم العميل"/><input name="phone" type="tel" pattern="(\+?20|0)1[0125][0-9]{8}" required placeholder="رقم واتساب مصري"/><textarea name="address" required placeholder="العنوان بالتفصيل"/><select name="payment"><option value="cod">الدفع عند الاستلام</option><option value="wallet" disabled={!onlineReady||!session}>{onlineReady?(session?'الدفع الإلكتروني / Paymob':'سجّل الدخول للدفع الإلكتروني'):'الدفع الإلكتروني — قيد التجهيز'}</option></select><div className="policy">{policy&&<><h4>{policy.title}</h4><p>{policy.body}</p><label><input type="checkbox" checked={policyAccepted} onChange={e=>setPolicyAccepted(e.target.checked)} required/> قرأت سياسة التوصيل وأوافق عليها</label></>}</div><div className="totals"><span>المنتجات</span><b>{subtotal.toLocaleString('ar-EG')} ج.م</b><span>الشحن</span><b>{shipping[gov].toLocaleString('ar-EG')} ج.م</b><strong>الإجمالي</strong><strong>{total.toLocaleString('ar-EG')} ج.م</strong></div>{msg&&<div className="notice">{msg}</div>}<button disabled={busy||!API||!policy||!policyAccepted||!deliveryGovernorates.includes(gov)} className="checkout">{busy?'جارٍ التنفيذ…':'تأكيد الطلب'}</button></form></>}</dialog>
 {compare&&<FullPageDialog className="modal product-page" label="تفاصيل المنتج ومقارنة الأسعار" onClose={()=>setCompare(null)}><div className="modalhead"><h2>تفاصيل المنتج ومقارنة الأسعار</h2><button onClick={()=>setCompare(null)}>×</button></div><ProductPage product={compare} products={products} onSelect={setCompare} onAdd={add} shipping={shipping} govLabels={govLabels} gov={gov} onGov={setGov} profile={profile}><div className="comparebox"><p>الأسعار المرصودة قد تتغير لدى المنافس. تحقق من المواصفات وتكلفة الشحن.</p>{comparisonError&&<p role="status">{comparisonError}</p>}{comparison.map((x,i)=><div className="line" key={i}><span>{storeName[x.competitor]||x.competitor}{x.observed_at&&<small className="comparison-time">آخر فحص: {new Date(x.observed_at).toLocaleString('ar-EG')}</small>}{safeSource(x.source_url)&&<a href={safeSource(x.source_url)} target="_blank" rel="noopener noreferrer">عرض المصدر</a>}</span><span><b>{Number(x.price).toLocaleString('ar-EG')} ج.م</b>{Number(x.price)>Number(compare.retail_price)&&<small className="comparison-time">توفير {Number(Number(x.price)-Number(compare.retail_price)).toLocaleString('ar-EG')} ج.م</small>}</span></div>)}{API&&!comparisonError&&!comparison.length&&<p>لا توجد مقارنة متاحة لهذا المنتج.</p>}<div className="our"><span>سعر اطلب ووفر</span><b>{Number(compare.retail_price).toLocaleString('ar-EG')} ج.م</b></div></div></ProductPage></FullPageDialog>}
 {invoice&&<FullPageDialog className="modal invoice-modal" label="الفاتورة" onClose={()=>setInvoice(null)}><div className="modalhead"><h2>فاتورة {invoice.order_number}</h2><button onClick={()=>setInvoice(null)}>×</button></div><Logo/><p>{invoice.customer_name}</p><p>{invoice.address} — {invoice.governorate}</p>{invoice.items.map((x,i)=><div className="line" key={i}><span>الكمية: {x.quantity}</span><b>{Number(x.line_total).toLocaleString('ar-EG')} ج.م</b></div>)}<div className="line"><span>الشحن</span><b>{invoice.shipping_fee} ج.م</b></div><div className="line"><b>الإجمالي</b><b>{invoice.total} ج.م</b></div><button className="checkout" onClick={()=>window.print()}>طباعة الفاتورة</button></FullPageDialog>}
 {accountOpen&&<FullPageDialog className="modal account-page" label="حساب العميل" onClose={()=>setAccountOpen(false)}><div className="modalhead"><h2>حساب العميل</h2><button aria-label="إغلاق الحساب" onClick={()=>setAccountOpen(false)}>×</button></div>{session?<><p>{session.user.email}</p><button className="checkout" onClick={async()=>{await customerAuth.auth.signOut();setAccountOpen(false)}}>تسجيل الخروج</button></>:<form onSubmit={accountAction}><label>البريد الإلكتروني<input type="email" name="email" required autoComplete="email"/></label><label>كلمة المرور<input type="password" name="password" minLength="8" required autoComplete="current-password"/></label><button className="checkout">دخول</button><button type="button" onClick={e=>accountAction({preventDefault(){},currentTarget:e.currentTarget.form},true)}>إنشاء حساب</button></form>}{authMessage&&<p role="status">{authMessage}</p>}</FullPageDialog>}
 {admin&&<FullPageDialog className="modal adminmodal admin-workspace" label="إدارة المتجر" onClose={()=>setAdmin(false)}><div className="modalhead"><h2>🔒 لوحة الإدارة</h2><button aria-label="العودة للمتجر" onClick={()=>setAdmin(false)}>العودة للمتجر ×</button></div>{!authed?<><p>أدخل مفتاح الإدارة. يبقى في الذاكرة لهذه الجلسة فقط.</p><input type="password" value={adminKey} onChange={e=>setAdminKey(e.target.value)} placeholder="Admin API Key"/><button className="checkout" onClick={login}>دخول آمن</button>{msg&&<p role="status">{msg}</p>}</>:<div className="adminpanel"><nav className="admintabs" aria-label="أقسام الإدارة"><button onClick={()=>setTab('kpi')}><BarChart3/> المؤشرات</button><button onClick={()=>setTab('orders')}>الطلبات</button><button onClick={()=>setTab('alerts')}>التنبيهات</button><button onClick={()=>setTab('review')}>مراجعة الربح</button><button onClick={()=>setTab('support')}>الإرجاع والشكاوى</button><button onClick={loadAdminProducts}><PackagePlus/> الأصناف</button><button onClick={()=>{setTab('suppliers');loadSuppliers().catch(e=>setMsg(e.message))}}><ShoppingBag/> الموردون</button><button onClick={()=>setTab('settings')}><Settings/> الإعدادات</button></nav><section className="admin-content" key={tab}><h2>{({kpi:"نظرة عامة",orders:"الطلبات ومتابعة التنفيذ",alerts:"التنبيهات والإجراءات",review:"مراجعة التسعير والربح",support:"الإرجاع والشكاوى",products:"الأصناف والمخزون",suppliers:"دليل الموردين",settings:"إعدادات المتجر"})[tab]}</h2>{tab==='kpi'&&<div className="kpis"><div><small>إجمالي المبيعات</small><b>{kpis.grossSales.toLocaleString('ar-EG')} ج.م</b></div><div><small>الطلبات المنفذة</small><b>{kpis.totalOrders}</b></div><div><small>الحالة</small><b>متصل</b></div></div>}{tab==='alerts'&&<AlertCenter api={API} adminKey={adminKey}/>}
{tab==='orders'&&<AdminOrders api={API} adminKey={adminKey}/>}
{tab==='support'&&<SupportRequests api={API} adminKey={adminKey}/>}
{tab==='review'&&<CatalogReview api={API} adminKey={adminKey}/>}
{tab==='suppliers'&&<SupplierDirectory api={API} adminKey={adminKey} suppliers={suppliers} onReload={loadSuppliers}/>}
{tab==='products'&&<div><button className="checkout" onClick={()=>setDraft({})}>إضافة صنف</button>{adminProducts.map(p=><div className="line" key={p.id}><span>{p.title_ar}</span><button onClick={()=>setDraft(p)}>تعديل</button></div>)}{draft&&<form onSubmit={saveProduct}><label>القسم<select name="category_id" defaultValue={draft.category_id||''}><option value="">بدون قسم</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name_ar}</option>)}</select></label><label>مصدر المنتج<select name="supplier_id" defaultValue={draft.supplier_id||''}><option value="">مخزوننا الخاص</option>{suppliers.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><p className="notice">كل لون ومقاس له كود صنف ومخزون مستقل. استخدم نفس كود الموديل لتجميع الاختيارات؛ المخزون غير المحصور يسجل صفرًا.</p><label>كود الموديل لتجميع الاختيارات<input name="model_key" defaultValue={draft.specifications?.model_key||''}/></label><label>اللون<input name="color" defaultValue={draft.specifications?.color||''}/></label><label>المقاس<input name="size" defaultValue={draft.specifications?.size||''}/></label><label>صور إضافية — رابط في كل سطر<textarea name="gallery_urls" defaultValue={draft.specifications?.gallery_urls||''}/></label><label>المواصفات الإضافية (JSON)<textarea name="specifications" defaultValue={JSON.stringify(draft.specifications||{},null,2)}/></label><input name="sku" required defaultValue={draft.sku||''} placeholder="كود المنتج" disabled={!!draft.id}/><input name="title_ar" required defaultValue={draft.title_ar||''} placeholder="اسم المنتج"/><label>المخزون (فارغ = توريد عند الطلب)<input name="stock_quantity" type="number" min="0" step="1" defaultValue={draft.stock_quantity??''}/></label><label>وصف المنتج<textarea name="description_ar" defaultValue={draft.description_ar||''}/></label><input name="image_url" type="url" defaultValue={draft.image_url||''} placeholder="رابط الصورة"/><label>تكلفة المورد<input name="supplier_cost" type="number" min="0.01" step=".01" required defaultValue={draft.supplier_cost||''}/></label><label>سعر البيع<input name="retail_price" type="number" min="0.01" step=".01" required defaultValue={draft.retail_price||''}/></label><label><input name="available" type="checkbox" defaultChecked={draft.available!==false}/> متاح للبيع</label><button className="checkout" disabled={busy}>حفظ</button><button type="button" onClick={()=>setDraft(null)}>إلغاء</button></form>}{msg&&<p role="status">{msg}</p>}</div>}{tab==='settings'&&<div className="settings"><div><Power/> الربط بالدفع والشحن والبحث يحتاج إعداد الخدمات قبل الإطلاق.</div><div>عنوان المحل: {profile?.address||'يحتاج تأكيدًا'}</div><div>التواصل: {profile?.phone||'يحتاج تأكيدًا'}</div><div>مواعيد العمل: {profile?.hours||'تحتاج تأكيدًا'}</div><div>الشحن: 35 / 50 / 60 / 65 / 75 ج.م حسب المحافظة.</div><a href={asset('admin.html')}>إدارة الطلبات والشحن والمطالبات</a></div>}</section></div>}</FullPageDialog>}
 {tracking&&<OrderTracking api={API} session={session} onClose={()=>setTracking(false)}/>}
 <DeliveryInterest api={API} available={deliveryGovernorates}/><footer><button onClick={()=>setTracking(true)}>متابعة طلبي والدفع</button><Logo/><p>تسوق بعناية. توصيل داخل مصر.</p><small>© {new Date().getFullYear()} اطلب ووفر</small></footer></div>}
createRoot(document.getElementById('root')).render(<App/>);

if('serviceWorker' in navigator && import.meta.env.PROD)window.addEventListener('load',()=>navigator.serviceWorker.register(asset('sw.js'),{scope:import.meta.env.BASE_URL}).catch(()=>{}));
