import {parseTrackingReference,makeTrackingLink} from './tracking-link.js';
import React,{useEffect,useRef,useState} from 'react';
import {SupportRequests} from './support-requests.jsx';
const paymentLabels={unpaid:'لم يُدفع',pending:'بانتظار التأكيد',requires_action:'بانتظار استكمال الدفع',authorized:'تفويض الدفع فقط',paid:'تم تأكيد الدفع',failed:'لم ينجح الدفع',refunded:'تم الاسترداد',partially_refunded:'استرداد جزئي',cancelled:'أُلغي الدفع'};
const orderLabels={pending:'طلب جديد',processing:'جارٍ التجهيز',confirmed:'تم التأكيد',shipped:'تم الشحن',delivered:'تم التسليم',cancelled:'ملغي',returned:'مرتجع',delivery_failed:'تعذر التسليم'};
export function OrderTracking({api,session,onClose}){
 const dialog=useRef(null),[order,setOrder]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[linkMessage,setLinkMessage]=useState(''),[referenceInput,setReferenceInput]=useState('');
 const load=async()=>{setBusy(true);setError('');try{let saved;try{saved=JSON.parse(sessionStorage.getItem('emad_last_invoice'))}catch{}if(!api)throw Error('متابعة الطلب متاحة بعد اتصال المتجر.');if(!saved?.id)throw Error('لا يوجد طلب محفوظ في هذا المتصفح. افتح المتابعة من الجهاز الذي أنشأت منه الطلب.');const authorization=saved.token?'invoice:'+saved.token:session?.access_token;if(!authorization)throw Error('سجّل الدخول للوصول إلى الطلب.');const r=await fetch(api+'/orders/'+encodeURIComponent(saved.id)+'/status',{headers:{Authorization:'Bearer '+authorization},cache:'no-store'});if(!r.ok)throw Error('تعذر التحقق من الطلب الآن. أعد المحاولة.');setOrder(await r.json())}catch(e){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{const reference=parseTrackingReference(location.hash);if(reference){sessionStorage.setItem('emad_last_invoice',JSON.stringify(reference));history.replaceState(null,'',location.pathname+location.search);}dialog.current.showModal();load()},[]);
 const copyLink=async()=>{try{const saved=JSON.parse(sessionStorage.getItem('emad_last_invoice'));const url=makeTrackingLink(saved,location.href);await navigator.clipboard.writeText(url);setLinkMessage('نُسخ رابط المتابعة. احتفظ به لنفسك؛ يتيح الاطلاع على طلبك.');}catch{setLinkMessage('تعذر النسخ التلقائي. افتح من خلال رابط المتابعة الخاص بطلبك أو أعد المحاولة.')}};
 const openReference=e=>{e.preventDefault();try{const url=new URL(referenceInput),reference=parseTrackingReference(url.hash);if(!reference)throw Error();sessionStorage.setItem('emad_last_invoice',JSON.stringify(reference));setReferenceInput('');load();}catch{setError('رابط المتابعة غير صحيح. استخدم الرابط الذي حصلت عليه بعد الطلب.')}};
 const retry=async()=>{setBusy(true);setError('');try{if(!session)throw Error('سجّل الدخول ثم أعد محاولة الدفع.');const r=await fetch(api+'/payments/paymob/intention',{method:'POST',headers:{'content-type':'application/json',Authorization:'Bearer '+session.access_token},body:JSON.stringify({orderId:order.id})});const data=await r.json();if(!r.ok||!data.checkout_url)throw Error('تعذر فتح بوابة الدفع. طلبك محفوظ، حاول لاحقًا.');location.assign(data.checkout_url)}catch(e){setError(e.message);setBusy(false)}};
 return <dialog ref={dialog} className="modal tracking-modal" onCancel={onClose}><div className="modalhead"><h2>متابعة الطلب والدفع</h2><button aria-label="إغلاق المتابعة" onClick={onClose}>×</button></div><form onSubmit={openReference}><label>لديك رابط متابعة؟ الصقه هنا<input type="text" value={referenceInput} onChange={e=>setReferenceInput(e.target.value)} autoComplete="off"/></label><button className="tracking-link">فتح الطلب من الرابط</button></form><p>نؤكد الدفع بعد وصول إشعار البوابة والتحقق منه. الرجوع من صفحة الدفع لا يكفي لتأكيده.</p>{order&&<><button className="tracking-link" onClick={copyLink}>نسخ رابط متابعة خاص لهذا الطلب</button>{linkMessage&&<p role="status">{linkMessage}</p>}<SupportRequests api={api} orderId={order.id} authorization={(()=>{try{const saved=JSON.parse(sessionStorage.getItem('emad_last_invoice'));return saved?.token?'invoice:'+saved.token:session?.access_token}catch{return session?.access_token}})()}/><h3>طلب {order.order_number}</h3><div className="line"><span>حالة الطلب</span><b>{orderLabels[order.status]||'تحت المراجعة'}</b></div><div className="line"><span>حالة الدفع</span><b>{paymentLabels[order.payment_status]||'بانتظار التحقق'}</b></div><div className="line"><span>الإجمالي</span><b>{Number(order.total).toLocaleString('ar-EG')} ج.م</b></div>{order.shipment&&<p>حالة الشحن: {order.shipment.status} {order.shipment.provider_awb}</p>}{order.payment_method==='wallet'&&!['paid','refunded','partially_refunded','authorized'].includes(order.payment_status)&&!['cancelled','returned','delivered'].includes(order.status)&&<button className="checkout" disabled={busy} onClick={retry}>استكمال الدفع لنفس الطلب</button>}</>}{error&&<p role="alert">{error}</p>}<button className="checkout" disabled={busy} onClick={load}>{busy?'جارٍ التحقق…':'تحديث حالة الطلب'}</button></dialog>
}
