import React,{useEffect,useState} from 'react';
import {ProductFacts} from './product-facts.jsx';
import {productChoices,productImages} from './catalog.js';
export function ProductPage({product,products,onSelect,onAdd,children,shipping,govLabels,gov,onGov,profile}) {
 const [photo,setPhoto]=useState(0),[zoom,setZoom]=useState(false);
 useEffect(()=>{setPhoto(0);setZoom(false)},[product.id]);
 const choices=productChoices(product,products),images=productImages(product),colors=[...new Set(choices.map(p=>p.specifications?.color).filter(Boolean))],sizes=[...new Set(choices.map(p=>p.specifications?.size).filter(x=>x!=null))];
 const select=(field,value)=>{const other=field==='size'?'color':'size';const found=choices.find(p=>String(p.specifications?.[field])===value&&String(p.specifications?.[other]??'')===String(product.specifications?.[other]??''))||choices.find(p=>String(p.specifications?.[field])===value);if(found)onSelect(found);};
 return <div className="product-detail-layout"><section className="product-gallery"><button className={'gallery-main '+(zoom?'is-zoomed':'')} onClick={()=>setZoom(x=>!x)} aria-label={zoom?'تصغير الصورة':'تكبير الصورة'}>{images.length?<img src={images[photo]||images[0]} alt={product.title_ar}/>:<p>الصورة غير متاحة</p>}</button><small>اضغط على الصورة للتكبير</small><div className="gallery-thumbnails">{images.map((url,i)=><button key={url} aria-label={'الصورة '+(i+1)} aria-pressed={photo===i} onClick={()=>{setPhoto(i);setZoom(false)}}><img src={url} alt=""/></button>)}</div></section><section><h1>{product.title_ar}</h1><p>{product.description_ar||'وصف المنتج لم يُستكمل بعد.'}</p><strong className="detail-price">{Number(product.retail_price).toLocaleString('ar-EG')} ج.م</strong><div className="choice-fields">{colors.length>0&&<label>اللون<select value={product.specifications?.color||''} onChange={e=>select('color',e.target.value)}>{colors.map(c=><option key={c}>{c}</option>)}</select></label>}{sizes.length>0&&<label>المقاس<select value={product.specifications?.size??''} onChange={e=>select('size',e.target.value)}>{sizes.map(s=><option key={s}>{s}</option>)}</select></label>}</div><p className="source-badge">{product.fulfillment_source==='owned'?'من مخزون المتجر':product.fulfillment_source==='supplier'?'توريد من مورد — التوفر يحتاج تأكيدًا':'مصدر المنتج يحتاج تأكيدًا'}</p><ProductFacts product={product}/><section className="delivery-summary"><h3>اعرف قبل ما تطلب</h3><label>محافظة التوصيل<select value={gov} onChange={e=>onGov(e.target.value)}>{Object.entries(govLabels).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><p>الشحن: {shipping[gov]} ج.م — إجمالي قطعة مع الشحن: {(Number(product.retail_price)+shipping[gov]).toLocaleString('ar-EG')} ج.م</p><p>موعد التسليم: {profile?.deliveryEstimate||'يُؤكد بعد مراجعة التوفر والعنوان.'}</p><p>الاستلام من المحل: {profile?.pickupAvailable?'تواصل معنا لتأكيد حجز المنتج وموعد الاستلام.':'يحتاج تأكيد عنوان المحل ومواعيد الاستلام.'}</p><p>الاستبدال والإرجاع حسب السياسة المنشورة وحالة المنتج. لا يوجد ضمان غير مذكور.</p></section><button className="checkout" disabled={product.stock_quantity===0||product.available===false} onClick={()=>onAdd(product)}>{product.stock_quantity===0?'غير متاح حاليًا':'إضافة الاختيار إلى السلة'}</button>{children}</section></div>;
}
