import React,{useEffect,useState,useRef} from 'react';
const kinds={return:'طلب إرجاع',cancellation:'طلب إلغاء',complaint:'شكوى'};
const states={pending:'بانتظار المراجعة',reviewing:'جارٍ المراجعة',resolved:'أُغلقت المعالجة',rejected:'لم يُقبل الطلب'};
export function SupportRequests({api,authorization,orderId,adminKey}) {
 const [rows,setRows]=useState([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const intent=useRef(null);
 const url=adminKey?api+'/admin/support':api+'/orders/'+encodeURIComponent(orderId)+'/support';
 const headers=adminKey?{'x-admin-key':adminKey}:{Authorization:'Bearer '+authorization};
 const load=async()=>{const r=await fetch(url,{headers,cache:'no-store'});if(!r.ok)throw Error();setRows(await r.json());};
 useEffect(()=>{load().catch(()=>setMessage('خدمة طلبات المساعدة غير متاحة الآن.'));},[url]);
 const submit=async e=>{e.preventDefault();setBusy(true);setMessage('');const form=e.currentTarget,f=new FormData(form),kind=f.get('kind'),text=f.get('message');const fingerprint=JSON.stringify([kind,text]);if(intent.current?.fingerprint!==fingerprint)intent.current={fingerprint,key:crypto.randomUUID()};try{const r=await fetch(url,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({kind,message:text,requestKey:intent.current.key})});if(!r.ok)throw Error();setMessage('تم تسجيل طلب المساعدة للمراجعة؛ لم يتم إلغاء الطلب أو رد المال تلقائيًا.');form.reset();intent.current=null;await load();}catch{setMessage('تعذر تأكيد تسجيل الطلب. أعد المحاولة بنفس البيانات.');}finally{setBusy(false);}};
 const reply=async(e,id)=>{e.preventDefault();setBusy(true);setMessage('');const f=new FormData(e.currentTarget);try{const r=await fetch(url+'/'+id,{method:'PATCH',headers:{...headers,'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});if(!r.ok)throw Error();await load();setMessage('حُفظ الرد؛ يراه العميل عند تحديث صفحة المتابعة.');}catch{setMessage('تعذر حفظ الرد.');}finally{setBusy(false);}};
 return <section><h3>{adminKey?'طلبات الإرجاع والشكاوى':'مساعدة بخصوص هذا الطلب'}</h3><p>هذه الخدمة تسجل طلب المراجعة فقط. الموافقة والإلغاء والشحن العكسي والاسترداد تُتابع بصورة منفصلة.</p>{!adminKey&&<form onSubmit={submit}><label>نوع المساعدة<select name="kind">{Object.entries(kinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>سبب الطلب والتفاصيل<textarea name="message" minLength={10} maxLength={2000} required/></label><button className="checkout" disabled={busy}>أرسل للمراجعة</button></form>}<button disabled={busy} onClick={()=>load().catch(()=>setMessage('تعذر تحديث طلبات المساعدة.'))}>تحديث طلبات المساعدة</button>{message&&<p role="status">{message}</p>}{rows.map(r=><article key={r.id}><h4>{kinds[r.kind]} — {states[r.status]}</h4>{adminKey&&<small>رقم الطلب: {r.order_id}</small>}<p>{r.message}</p>{r.customer_reply&&<p>رد المتجر: {r.customer_reply}</p>}{adminKey&&<form onSubmit={e=>reply(e,r.id)}><label>الحالة<select aria-label="الحالة" name="status" defaultValue={r.status}>{Object.entries(states).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>رد يظهر للعميل<textarea name="customer_reply" maxLength={2000} defaultValue={r.customer_reply}/></label><button disabled={busy}>حفظ الرد والحالة</button></form>}</article>)}</section>;
}
