import React,{useState} from 'react';
const methods={automatic:'طلب آلي بعد الربط',contact:'اتصال بالمورد',visit:'زيارة وشراء من المكان'};
export function SupplierDirectory({api,adminKey,suppliers,onReload}){
 const [draft,setDraft]=useState(null),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const save=async e=>{e.preventDefault();setBusy(true);setMessage('');const data=Object.fromEntries(new FormData(e.currentTarget));for(const k of ['allows_single_units','direct_fulfillment','active'])data[k]=data[k]==='on';data.min_order_quantity=Number(data.min_order_quantity);
  try{const r=await fetch(api+'/admin/suppliers'+(draft.id?'/'+draft.id:''),{method:draft.id?'PATCH':'POST',headers:{'content-type':'application/json','x-admin-key':adminKey},body:JSON.stringify(data)});if(!r.ok)throw Error('تعذر الحفظ. راجع التواصل والحد الأدنى للشراء؛ بيع القطعة يتطلب حدًا أدنى قطعة واحدة.');await onReload();setDraft(null);setMessage('تم حفظ المورد');}catch(e){setMessage(e.message)}finally{setBusy(false)}
 };
 return <section className="supplier-directory"><h3>دليل الموردين والتجار</h3><p>سجل شروط الشراء والتواصل. اختيار «طلب آلي» يحدد الطريقة المطلوبة؛ التفعيل يحتاج ربط المورد وتأكيد شروطه.</p><label>البحث في الدليل<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="الاسم أو الهاتف أو العنوان…"/></label><button className="checkout" onClick={()=>setDraft({active:true})}>إضافة مورد أو تاجر</button>
 {suppliers.filter(s=>[s.name,s.phone,s.whatsapp_phone,s.address,s.notes].join(' ').includes(query)).map(s=><article className="supplier-card" key={s.id}><h4>{s.name} {!s.active&&'— غير نشط'}</h4><p>{methods[s.order_method]} · {s.allows_single_units?'يبيع بالقطعة':'بيع القطعة غير مؤكد / جملة'} · الحد الأدنى: {s.min_order_quantity} · {s.direct_fulfillment?'يوافق على الشحن المباشر':'الشحن المباشر غير مؤكد'}</p><p>{s.contact_name} {s.address}</p><div className="supplier-contacts">{s.phone&&<a href={'tel:'+s.phone.replace(/[^+0-9]/g,'')}>هاتف: {s.phone}</a>}{s.whatsapp_phone&&<a target="_blank" rel="noopener noreferrer" href={'https://wa.me/'+s.whatsapp_phone.replace(/\D/g,'').replace(/^0/,'20')}>واتساب: {s.whatsapp_phone}</a>}{s.email&&<a href={'mailto:'+s.email}>البريد: {s.email}</a>}{s.website&&<a target="_blank" rel="noopener noreferrer" href={s.website}>موقع المورد</a>}</div><p>{s.notes}</p><button onClick={()=>setDraft(s)}>تعديل السجل</button></article>)}
 {draft&&<form onSubmit={save}><h4>{draft.id?'تعديل مورد':'مورد جديد'}</h4>{[['name','اسم المورد أو المتجر'],['contact_name','اسم مسؤول التواصل'],['phone','الهاتف'],['whatsapp_phone','واتساب مع كود الدولة'],['email','البريد الإلكتروني'],['website','الموقع الإلكتروني'],['source_url','رابط المصدر الذي عثرنا عليه'],['address','عنوان الزيارة أو الاستلام']].map(([name,label])=><label key={name}>{label}<input name={name} defaultValue={draft[name]||''} required={name==='name'} type={['website','source_url'].includes(name)?'url':name==='email'?'email':'text'}/></label>)}<label>طريقة إتمام الشراء<select name="order_method" defaultValue={draft.order_method||'contact'}>{Object.entries(methods).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>الحد الأدنى للشراء<input type="number" min="1" step="1" name="min_order_quantity" defaultValue={draft.min_order_quantity||1} required/></label><label><input type="checkbox" name="allows_single_units" defaultChecked={draft.allows_single_units}/> تأكدت أن المورد يبيع قطعة واحدة</label><label><input type="checkbox" name="direct_fulfillment" defaultChecked={draft.direct_fulfillment}/> يوافق على الشحن مباشرة لعميلنا</label><label><input type="checkbox" name="active" defaultChecked={draft.active!==false}/> مورد نشط</label><label>ملاحظات سعر القطعة والجملة، مواعيد التواصل، الشحن والمرتجعات<textarea name="notes" defaultValue={draft.notes||''}/></label><button className="checkout" disabled={busy}>حفظ المورد</button><button type="button" onClick={()=>setDraft(null)}>إلغاء</button></form>}{message&&<p role="status">{message}</p>}</section>;
}
