import {paymobStatus} from '../../../shared/paymob-status.js';
import express from 'express';import helmet from 'helmet';import cors from 'cors';import crypto from 'crypto';
import {requireAdmin} from './admin.js';import {createClient} from '@supabase/supabase-js';import {createPaymobIntention,createBostaDelivery,sendSupplierWhatsApp,verifyPaymobTransactionHmac} from './integrations.js';
const app=express();app.set('trust proxy', 1);app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}}));app.use(cors({origin:process.env.PUBLIC_ORIGIN?.split(',')||false}));app.use('/webhooks/paymob', express.raw({type:'application/json', limit:'1mb'}));
const buckets=new Map();
setInterval(()=>{const now=Date.now();for(const [key,b] of buckets)if(now-b.t>60_000)buckets.delete(key)},60_000).unref();
const rateLimit=(limit,windowMs)=> (req,res,next)=>{const k=req.baseUrl+':'+req.ip;const now=Date.now();const b=buckets.get(k)||{n:0,t:now};if(now-b.t>windowMs){b.n=0;b.t=now;}b.n++;buckets.set(k,b);if(b.n>limit)return res.status(429).json({error:'rate_limited'});next();};
app.use(express.json({limit:'1mb'}));
app.use('/orders',rateLimit(12,60_000));
app.use('/payments',rateLimit(20,60_000));const SUPABASE_SERVER_KEY=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY;
if(!process.env.SUPABASE_URL||!SUPABASE_SERVER_KEY) throw new Error('Missing Supabase server configuration');
const supabase=createClient(process.env.SUPABASE_URL,SUPABASE_SERVER_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const ship={FAYOUM:35,CAIRO:50,GIZA:50,ALEXANDRIA:60,DELTA_CANAL:65,UPPER_EGYPT:75};
import {calculatePrice} from './pricing.js';
import {quoteSources,searchSourceFeeds} from './sourcing.js';
import {supplierRecord} from './suppliers.js';
app.get('/admin/suppliers',requireAdmin,async(req,res)=>{res.set('Cache-Control','no-store');const {data,error}=await supabase.from('suppliers').select('*').order('name');if(error)return res.status(503).json({error:'supplier_directory_unavailable'});res.json(data||[])});
app.post('/admin/suppliers',requireAdmin,async(req,res)=>{try{const row=supplierRecord(req.body||{});const {data,error}=await supabase.from('suppliers').insert(row).select('*').single();if(error)return res.status(503).json({error:'supplier_save_failed'});res.status(201).json(data)}catch{res.status(400).json({error:'invalid_supplier_record'})}});
app.patch('/admin/suppliers/:id',requireAdmin,async(req,res)=>{try{const row=supplierRecord(req.body||{});const {data,error}=await supabase.from('suppliers').update(row).eq('id',req.params.id).select('*').single();if(error)return res.status(503).json({error:'supplier_save_failed'});res.json(data)}catch{res.status(400).json({error:'invalid_supplier_record'})}});
app.get('/catalog/search',rateLimit(10,60_000),async(req,res)=>{
 res.set('Cache-Control','no-store');
 try{
  const config=JSON.parse(process.env.APPROVED_SOURCE_FEEDS||'[]');
  if(!config.length)return res.status(503).json({error:'external_search_not_configured'});
  const feeds=config.map(f=>({...f,token:f.tokenEnv?process.env[f.tokenEnv]:undefined}));
  const results=await searchSourceFeeds(req.query.q,{feeds});
  const quotes=quoteSources(results.offers).map(({supplierId,pricing,...q})=>({...q,price:pricing?.finalPrice??null}));
  res.json({quotes,sourcesChecked:results.sourcesChecked,sourcesUnavailable:results.sourcesUnavailable,preview:true});
 }catch{res.status(400).json({error:'external_search_unavailable'});}
});
// A read-only order quote. It does not change catalog prices or activate payment fees.
app.post('/admin/pricing/preview',requireAdmin,(req,res)=>{
 try{res.json({preview:true,...calculatePrice({...req.body,emergencyApproved:false})});}
 catch{res.status(400).json({error:'invalid_pricing_inputs'});}
});
app.get('/policies',async(req,res)=>{const {data,error}=await supabase.from('store_policies').select('version,title,body').eq('active',true).eq('policy_type','shipping_non_delivery').order('created_at',{ascending:false}).limit(1);if(error)return res.status(500).json({error:'policies_unavailable'});res.json(data?.[0]||null)});
app.get('/capabilities',(req,res)=>res.json({onlinePayment:process.env.PAYMOB_ONLINE_ENABLED==='true'&&!!process.env.PAYMOB_SECRET_KEY&&!!process.env.PAYMOB_PUBLIC_KEY&&!!process.env.PAYMOB_INTEGRATION_IDS&&!!process.env.PAYMOB_NOTIFICATION_URL&&!!process.env.PAYMOB_REDIRECTION_URL}));
app.get('/health',(req,res)=>res.json({ok:true,service:'emad-store-api',time:new Date().toISOString()}));
app.get('/products',async(req,res)=>{try{const {data,error}=await supabase.from('products').select('id,sku,title_ar,category_id,image_url,retail_price,available,description_ar,stock_quantity,category:categories(slug)').eq('available',true).order('created_at',{ascending:false});if(error)throw error;res.json((data||[]).map(({category,...p})=>({...p,category_slug:category?.slug})));}catch(e){res.status(500).json({error:'products_failed'});}});
app.get('/products/:id/compare',async(req,res)=>{try{
 const {data,error}=await supabase.rpc('public_price_compare',{p_product_id:req.params.id});if(error)throw error;
 const observations=await supabase.from('competitors_pricing').select('competitor,price,source_url,observed_at').eq('product_id',req.params.id).eq('verified_match',true).gte('observed_at',new Date(Date.now()-48*3600000).toISOString()).order('observed_at',{ascending:false}).order('id',{ascending:false});
 if(observations.error)throw observations.error;
 res.json((data||[]).map(row=>({...row,...observations.data.find(x=>x.competitor===row.competitor&&Number(x.price)===Number(row.price))})));
}catch(e){res.status(500).json({error:'compare_failed'});}});

app.get('/admin/products',requireAdmin,async(req,res)=>{try{const {data,error}=await supabase.from('products').select('id,sku,title_ar,category_id,image_url,retail_price,supplier_cost,available,stock_quantity,description_ar,specifications,supplier_id,pricing_updated_at,created_at').order('created_at',{ascending:false});if(error)throw error;res.json(data||[]);}catch(e){res.status(500).json({error:'admin_products_failed'});}});
app.post('/admin/products',requireAdmin,async(req,res)=>{try{const b=req.body||{};if(!b.sku||!b.title_ar||b.supplier_cost==null) return res.status(400).json({error:'sku,title_ar,supplier_cost required'});if(!Number.isFinite(Number(b.supplier_cost))||Number(b.supplier_cost)<=0||!Number.isFinite(Number(b.retail_price))||Number(b.retail_price)<Math.ceil(Number(b.supplier_cost)*1.055*100-1e-8)/100)return res.status(400).json({error:'price_below_normal_floor'});const row={sku:b.sku,title_ar:b.title_ar,category_id:b.category_id||null,image_url:b.image_url||null,retail_price:Number(b.retail_price||0),supplier_cost:Number(b.supplier_cost),available:b.available!==false,stock_quantity:b.stock_quantity==null?null:Number(b.stock_quantity),description_ar:String(b.description_ar||'').slice(0,5000),specifications:b.specifications||{},supplier_id:b.supplier_id||null};const {data,error}=await supabase.from('products').insert(row).select('id,sku,title_ar,category_id,image_url,retail_price,available').single();if(error)throw error;res.status(201).json(data);}catch(e){res.status(500).json({error:'admin_product_create_failed'});}});
app.patch('/admin/products/:id',requireAdmin,async(req,res)=>{try{const allowed=['title_ar','category_id','image_url','retail_price','supplier_cost','available','supplier_id','stock_quantity','description_ar','specifications'];const before=await supabase.from('products').select('supplier_cost,retail_price').eq('id',req.params.id).single();if(before.error)return res.status(404).json({error:'product_not_found'});const cost=Number(req.body.supplier_cost??before.data.supplier_cost),price=Number(req.body.retail_price??before.data.retail_price);if(!Number.isFinite(cost)||cost<=0||!Number.isFinite(price)||price<Math.ceil(cost*1.055*100-1e-8)/100)return res.status(400).json({error:'price_below_normal_floor'});const patch=Object.fromEntries(Object.entries(req.body||{}).filter(([k])=>allowed.includes(k)));const {data,error}=await supabase.from('products').update(patch).eq('id',req.params.id).select('id,sku,title_ar,category_id,image_url,retail_price,available').single();if(error)throw error;res.json(data);}catch(e){res.status(500).json({error:'admin_product_update_failed'});}});
app.delete('/admin/products/:id',requireAdmin,async(req,res)=>{try{const {error}=await supabase.from('products').update({available:false}).eq('id',req.params.id);if(error)throw error;res.status(204).end();}catch(e){res.status(500).json({error:'admin_product_delete_failed'});}});
app.get('/admin/kpis',requireAdmin,async(req,res)=>{try{const {data,error}=await supabase.from('orders').select('subtotal,total,status,payment_status');if(error)throw error;const rows=data||[];const executed=rows.filter(x=>['confirmed','fulfilled','delivered'].includes(x.status)&&x.payment_status!=='failed');const sales=executed.reduce((s,x)=>s+Number(x.total),0);res.json({grossSales:sales,totalOrders:executed.length});}catch(e){res.status(500).json({error:'kpi_failed'});}});
app.post('/pricing/recalculate',requireAdmin,async(req,res)=>{const {data,error}=await supabase.rpc('recalculate_price_v18',{p_product_id:req.body.productId});if(error)return res.status(409).json({error:'pricing_blocked_or_missing_verified_comparison'});res.json(data)});
app.post('/admin/competitors',requireAdmin,async(req,res)=>{try{const b=req.body;if(!['amazon','noon','btech'].includes(b.competitor)||!Number.isFinite(Number(b.price))||Number(b.price)<=0||b.verified_match!==true)return res.status(400).json({error:'verified_match_and_positive_price_required'});const u=new URL(b.source_url);if(u.protocol!=='https:')return res.status(400).json({error:'https_source_required'});const {data,error}=await supabase.from('competitors_pricing').insert({product_id:b.product_id,competitor:b.competitor,price:Number(b.price),source_url:u.href,verified_match:true,match_note:String(b.match_note||'').slice(0,1000)}).select('id,competitor,price').single();if(error)throw error;res.status(201).json(data)}catch{return res.status(400).json({error:'invalid_competitor_record'})}});

async function canReadOrder(req){const token=req.get('Authorization')?.replace(/^Bearer /,'')||'';const expected=crypto.createHmac('sha256',SUPABASE_SERVER_KEY).update('invoice:'+req.params.id).digest('hex');let allowed=false;if(token.startsWith('invoice:')){const raw=Buffer.from(token.slice(8)),want=Buffer.from(expected);allowed=raw.length===want.length&&crypto.timingSafeEqual(raw,want)}else if(token){const auth=await supabase.auth.getUser(token);if(auth.data.user){const owner=await supabase.from('orders').select('user_id').eq('id',req.params.id).maybeSingle();allowed=owner.data?.user_id===auth.data.user.id}}return allowed;}
app.get('/orders/:id/status',async(req,res)=>{try{res.set('Cache-Control','no-store');if(!await canReadOrder(req))return res.status(403).json({error:'forbidden'});const {data,error}=await supabase.from('orders').select('id,order_number,status,payment_status,payment_method,total').eq('id',req.params.id).maybeSingle();if(error||!data)return res.status(404).json({error:'order_not_found'});const shipment=await supabase.from('shipments').select('status,provider_awb').eq('order_id',req.params.id).maybeSingle();if(shipment.error)return res.status(503).json({error:'shipment_status_unavailable'});res.json({...data,shipment:shipment.data});}catch{res.status(503).json({error:'status_unavailable'})}});
app.get('/orders/:id/invoice',async(req,res)=>{try{res.set('Cache-Control','no-store');if(!await canReadOrder(req))return res.status(403).json({error:'forbidden'});const {data,error}=await supabase.rpc('get_order_invoice',{p_order_id:req.params.id});if(error||!data)return res.status(404).json({error:'invoice_not_found'});res.json(data)}catch{res.status(503).json({error:'invoice_unavailable'})}});
app.get('/categories',async(req,res)=>{const {data,error}=await supabase.from('categories').select('id,slug,name_ar').order('name_ar');if(error)return res.status(500).json({error:'categories_failed'});res.json(data||[])});
app.post('/orders',async(req,res)=>{try{
 const {customer_name,whatsapp_phone,governorate,address,payment_method,items}=req.body;
 if(payment_method==='wallet'&&process.env.PAYMOB_ONLINE_ENABLED!=='true')return res.status(503).json({error:'online_payment_not_enabled'});const idem=req.get('Idempotency-Key');if(!idem||idem.length<16||idem.length>200)return res.status(400).json({error:'invalid_idempotency_key'});
 if(!customer_name||!address||!Array.isArray(items)||!items.length||items.length>30||items.some(x=>!Number.isInteger(x.quantity)||x.quantity<1||x.quantity>100))return res.status(400).json({error:'invalid_order'});
 let userId=null;const token=req.get('Authorization')?.replace(/^Bearer /,'');if(token){const {data,error}=await supabase.auth.getUser(token);if(error||!data.user)return res.status(401).json({error:'unauthorized'});userId=data.user.id}
 const {data,error}=await supabase.rpc('create_order_v18',{p_key:idem,p_customer_name:customer_name,p_whatsapp_phone:whatsapp_phone,p_governorate:governorate,p_address:address,p_payment_method:payment_method||'cod',p_items:items,p_user_id:userId,p_policy_version:req.body.policy_version,p_policy_accepted:req.body.policy_accepted===true});
 if(error)return res.status(409).json({error:'order_validation_failed'});const order=Array.isArray(data)?data[0]:data;const invoice_token=crypto.createHmac('sha256',SUPABASE_SERVER_KEY).update('invoice:'+order.id).digest('hex');res.status(order.replayed?200:201).json({...order,invoice_token});
 }catch(e){res.status(500).json({error:'order_failed'})}});

app.post('/payments/paymob/intention',async(req,res)=>{try{const token=req.get('Authorization')?.replace(/^Bearer /,'');if(!token)return res.status(401).json({error:'unauthorized'});const auth=await supabase.auth.getUser(token);if(auth.error||!auth.data.user)return res.status(401).json({error:'unauthorized'});const {orderId}=req.body;if(process.env.PAYMOB_ONLINE_ENABLED!=='true')return res.status(503).json({error:'online_payment_not_enabled'});if(!orderId)return res.status(400).json({error:'orderId_required'});const {data:o,error}=await supabase.from('orders').select('id,order_number,total,customer_name,whatsapp_phone,governorate,address,payment_status,user_id,payment_method,status').eq('id',orderId).single();if(error||!o)return res.status(404).json({error:'order_not_found'});if(o.user_id!==auth.data.user.id)return res.status(403).json({error:'forbidden'});if(o.payment_method!=='wallet'||['cancelled','returned','delivered'].includes(o.status))return res.status(409).json({error:'order_not_payable'});if(['paid','authorized','refunded','partially_refunded'].includes(o.payment_status))return res.status(409).json({error:'already_paid'});const existing=await supabase.from('payment_intents').select('checkout_url,status,metadata').eq('order_id',orderId).maybeSingle();if(existing.error)throw existing.error;if(existing.data?.checkout_url&&['pending','requires_action'].includes(existing.data.status)&&Date.parse(existing.data.metadata?.expires_at||'')>Date.now())return res.json({checkout_url:existing.data.checkout_url,order_id:orderId,reused:true});const {data:items,error:itemsError}=await supabase.from('order_items').select('quantity,unit_price,product:products(title_ar,sku)').eq('order_id',orderId);if(itemsError||!items?.length)throw Error('items_unavailable');const creationToken=crypto.randomUUID();const claim=await supabase.rpc('claim_paymob_creation',{p_order_id:orderId,p_token:creationToken});if(claim.error)throw claim.error;if(claim.data?.state==='reused')return res.json({checkout_url:claim.data.checkout_url,order_id:orderId,reused:true});if(claim.data?.state!=='claimed')return res.status(409).json({error:'payment_creation_requires_review'});const intention=await createPaymobIntention({amountEGP:Number(o.total),reference:o.order_number,customer:{name:o.customer_name,phone:o.whatsapp_phone,address:o.address,governorate:o.governorate},items:(items||[]).map(x=>({name:x.product?.title_ar||'Emad Store item',amount:x.unit_price,quantity:x.quantity} ))});const base=(process.env.PAYMOB_BASE_URL||'https://accept.paymob.com').replace(/\/$/,'');if(!intention.client_secret||!intention.id||!(intention.intention_order_id||intention.order?.id))throw new Error('invalid_paymob_response');const checkout_url=base+'/unifiedcheckout/?publicKey='+encodeURIComponent(process.env.PAYMOB_PUBLIC_KEY)+'&clientSecret='+encodeURIComponent(intention.client_secret);
 const saved=await supabase.rpc('finish_paymob_creation',{p_order_id:orderId,p_token:creationToken,p_row:{order_id:orderId,provider:'paymob',provider_order_id:String(intention.intention_order_id||intention.order?.id||''),intention_id:String(intention.id),amount:Number(o.total),currency:'EGP',status:'requires_action',checkout_url,client_secret:intention.client_secret,metadata:{expires_at:new Date(Date.now()+45*60*1000).toISOString()}}});if(saved.error)throw saved.error;
 res.json({checkout_url,order_id:orderId});}catch(e){res.status(502).json({error:'paymob_intention_failed'});}});

app.post('/admin/orders/:id/dispatch',requireAdmin,async(req,res)=>{const {data:order,error}=await supabase.from('orders').select('id,payment_method,payment_status,status').eq('id',req.params.id).single();if(error)return res.status(404).json({error:'order_not_found'});if(order.payment_method!=='cod'&&order.payment_status!=='paid')return res.status(409).json({error:'payment_not_confirmed'});if(['cancelled','returned','delivered'].includes(order.status))return res.status(409).json({error:'order_not_dispatchable'});const queued=await supabase.rpc('enqueue_fulfillment_for_paid_order',{p_order_id:order.id});if(queued.error)return res.status(500).json({error:'queue_failed'});res.status(202).json({ok:true,queued:true})});
app.post('/webhooks/paymob',async(req,res)=>{try{const payload=Buffer.isBuffer(req.body)?JSON.parse(req.body.toString('utf8')):req.body;const obj=payload?.obj||payload;const signature=req.query.hmac||req.get('hmac')||req.get('x-paymob-hmac')||'';if(!verifyPaymobTransactionHmac(obj,process.env.PAYMOB_HMAC_SECRET,signature))return res.status(401).json({error:'invalid_hmac'});const integrations=(process.env.PAYMOB_INTEGRATION_IDS||'').split(',').map(x=>x.trim()).filter(Boolean);if(!integrations.includes(String(obj.integration_id)))return res.status(403).json({error:'integration_not_allowed'});const eventId=String(obj.id||payload.id||'');if(!eventId)return res.status(400).json({error:'missing_event_id'});const ref=obj.order?.merchant_order_id||obj.order?.merchant_order_id||obj.payment_key_claims?.extra?.order_number;let orderQuery=null;if(ref)orderQuery=await supabase.from('orders').select('id,total,payment_status,status').eq('order_number',ref).maybeSingle();if(!orderQuery?.data&&obj.order?.id){const pi=await supabase.from('payment_intents').select('order_id').eq('provider_order_id',String(obj.order.id)).maybeSingle();if(pi.data)orderQuery=await supabase.from('orders').select('id,total,payment_status,status').eq('id',pi.data.order_id).single();}if(!orderQuery?.data)return res.status(404).json({error:'order_not_found'});
 const status=await paymobStatus(obj,{apiKey:process.env.PAYMOB_API_KEY,baseUrl:process.env.PAYMOB_BASE_URL});
 const applied=await supabase.rpc('apply_paymob_event_v18',{p_order_id:orderQuery.data.id,p_event_id:eventId+':'+status,p_status:status,p_amount_cents:Number(obj.amount_cents),p_currency:obj.currency,p_provider_order_id:String(obj.order?.id||''),p_payload:payload});if(applied.error)return res.status(409).json({error:'payment_update_failed'});
 res.json({received:true});}catch(e){res.status(500).json({error:'webhook_failed'});}});
export {app};
if(process.env.NODE_ENV!=='test')app.listen(process.env.PORT||8080,()=>console.log('API listening'));
